// estadios brasileiros: { cidade, estado, uf }
// estadios internacionais: { cidade, pais, codigo } (codigo = ISO 2 letras para flag-icons)

const estadiosLocais = {
    "Allianz Parque":                       { cidade: "São Paulo", estado: "São Paulo", uf: "SP" },
    "Arena Condá":                          { cidade: "Chapecó", estado: "Santa Catarina", uf: "SC" },
    "Arena MRV":                            { cidade: "Contagem", estado: "Minas Gerais", uf: "MG" },
    "Arena da Baixada":                     { cidade: "Curitiba", estado: "Paraná", uf: "PR" },
    "Arena do Grêmio":                      { cidade: "Porto Alegre", estado: "Rio Grande do Sul", uf: "RS" },
    "Barradão":                             { cidade: "Salvador", estado: "Bahia", uf: "BA" },
    "Caio Martins":                         { cidade: "Niterói", estado: "Rio de Janeiro", uf: "RJ" },
    "Centenario-URU":                       { cidade: "Montevidéu", pais: "Uruguai", codigo: "uy" },
    "Conselheiro Galvão":                   { cidade: "Campos dos Goytacazes", estado: "Rio de Janeiro", uf: "RJ" },
    "Couto Pereira":                        { cidade: "Curitiba", estado: "Paraná", uf: "PR" },
    "Elcyr Resende":                        { cidade: "Bacaxá", estado: "Rio de Janeiro", uf: "RJ" },
    "Independência":                        { cidade: "Belo Horizonte", estado: "Minas Gerais", uf: "MG" },
    "Jair Toscano":                         { cidade: "Macaé", estado: "Rio de Janeiro", uf: "RJ" },
    "Joaquim de Morais Filho":              { cidade: "Taubaté", estado: "São Paulo", uf: "SP" },
    "Kleber Andrade":                       { cidade: "Cariacica", estado: "Espírito Santo", uf: "ES" },
    "Lourivaldão":                          { cidade: "Saquarema", estado: "Rio de Janeiro", uf: "RJ" },
    "Luso Brasileiro":                      { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Maracanã":                             { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Mineirão":                             { cidade: "Belo Horizonte", estado: "Minas Gerais", uf: "MG" },
    "Monumental de Núñez":                  { cidade: "Buenos Aires", pais: "Argentina", codigo: "ar" },
    "Morumbi":                              { cidade: "São Paulo", estado: "São Paulo", uf: "SP" },
    "Moça Bonita":                          { cidade: "Nova Iguaçu", estado: "Rio de Janeiro", uf: "RJ" },
    "Mário Helênio":                        { cidade: "Juiz de Fora", estado: "Minas Gerais", uf: "MG" },
    "Nabi Abi Chedid":                      { cidade: "Bragança Paulista", estado: "São Paulo", uf: "SP" },
    "Neo Química Arena":                    { cidade: "São Paulo", estado: "São Paulo", uf: "SP" },
    "Nilton Santos":                        { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Raulino de Oliveira":                  { cidade: "Volta Redonda", estado: "Rio de Janeiro", uf: "RJ" },
    "São Januário":                         { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Vila Belmiro":                         { cidade: "Santos", estado: "São Paulo", uf: "SP" },
    "Fonte Nova":                           { cidade: "Salvador", estado: "Bahia", uf: "BA" },
    "General Severiano":                    { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Gávea":                                { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Ilha do Retiro":                       { cidade: "Recife", estado: "Pernambuco", uf: "PE" },
    "Laranjeiras":                          { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Mané Garrincha":                       { cidade: "Brasília", estado: "Distrito Federal", uf: "DF" },
    "Pacaembu":                             { cidade: "São Paulo", estado: "São Paulo", uf: "SP" },
    "Acúrcio Torres":                       { cidade: "Cantagalo", estado: "Rio de Janeiro", uf: "RJ" },
    "Adautão":                              { cidade: "Juazeiro", estado: "Bahia", uf: "BA" },
    "Adolfo Konder":                        { cidade: "Florianópolis", estado: "Santa Catarina", uf: "SC" },
    "Aflitos":                              { cidade: "Recife", estado: "Pernambuco", uf: "PE" },
    "Afonso de Carvalho":                   { cidade: "Ubá", estado: "Minas Gerais", uf: "MG" },
    "Alania":                               { cidade: "Vladikavkaz", pais: "Rússia", codigo: "ru" },
    "Albertão":                             { cidade: "Teresina", estado: "Piauí", uf: "PI" },
    "Alejandro Villanueva":                 { cidade: "La Victoria", pais: "Peru", codigo: "pe" },
    "Alfredo Jaconi":                       { cidade: "Caxias do Sul", estado: "Rio Grande do Sul", uf: "RS" },
    "Alfredão":                             { cidade: "Bauru", estado: "São Paulo", uf: "SP" },
    "Almeidão":                             { cidade: "João Pessoa", estado: "Paraíba", uf: "PB" },
    "Aluizão":                              { cidade: "Ji-Paraná", estado: "Rondônia", uf: "RO" },
    "Amaro Lanari Júnior":                  { cidade: "Ipatinga", estado: "Minas Gerais", uf: "MG" },
    "Amigão":                               { cidade: "Campina Grande", estado: "Paraíba", uf: "PB" },
    "Anacleto Campanella":                  { cidade: "São Caetano do Sul", estado: "São Paulo", uf: "SP" },
    "Annibal Batista de Toledo":            { cidade: "Aparecida de Goiânia", estado: "Goiás", uf: "GO" },
    "Antonio Accioly":                      { cidade: "Goiânia", estado: "Goiás", uf: "GO" },
    "Arena Acreana":                        { cidade: "Rio Branco", estado: "Acre", uf: "AC" },
    "Arena Barueri":                        { cidade: "Barueri", estado: "São Paulo", uf: "SP" },
    "Arena Pantanal":                       { cidade: "Cuiabá", estado: "Mato Grosso", uf: "MT" },
    "Arena da Amazônia":                    { cidade: "Manaus", estado: "Amazonas", uf: "AM" },
    "Arena de Pernambuco":                  { cidade: "São Lourenço da Mata", estado: "Pernambuco", uf: "PE" },
    "Arena do Jacaré":                      { cidade: "Sete Lagoas", estado: "Minas Gerais", uf: "MG" },
    "Arruda":                               { cidade: "Recife", estado: "Pernambuco", uf: "PE" },
    "Artemio Franchi":                      { cidade: "Florença", pais: "Itália", codigo: "it" },
    "Arthur Marinho":                       { cidade: "Corumbá", estado: "Mato Grosso do Sul", uf: "MS" },
    "Aryzão":                               { cidade: "Campos dos Goytacazes", estado: "Rio de Janeiro", uf: "RJ" },
    "Atanasio Girardot":                    { cidade: "Medellín", pais: "Colômbia", codigo: "co" },
    "Atilio Marotti":                       { cidade: "Petrópolis", estado: "Rio de Janeiro", uf: "RJ" },
    "Augustinho Lima":                      { cidade: "Sobradinho", estado: "Distrito Federal", uf: "DF" },
    "Augusto Bauer":                        { cidade: "Brusque", estado: "Santa Catarina", uf: "SC" },
    "Augusto Simões Lopes":                 { cidade: "Sede", estado: "Rio Grande do Sul", uf: "RS" },
    "Avenida Araguaya":                     { cidade: "Belo Horizonte", estado: "Minas Gerais", uf: "MG" },
    "Azteca":                               { cidade: "Cidade do México", pais: "México", codigo: "mx" },
    "Baenão":                               { cidade: "Belém", estado: "Pará", uf: "PA" },
    "Baixada da Água Verde":                { cidade: "Curitiba", estado: "Paraná", uf: "PR" },
    "Balaídos":                             { cidade: "Vigo", pais: "Espanha", codigo: "es" },
    "Barão de São Francisco Filho":         { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Batistão":                             { cidade: "Aracaju", estado: "Sergipe", uf: "SE" },
    "Beira-Rio":                            { cidade: "Porto Alegre", estado: "Rio Grande do Sul", uf: "RS" },
    "Benedito Teixeira":                    { cidade: "São José do Rio Preto", estado: "São Paulo", uf: "SP" },
    "Bento de Abreu":                       { cidade: "Marília", estado: "São Paulo", uf: "SP" },
    "Bento de Freitas":                     { cidade: "Bagé", estado: "Rio Grande do Sul", uf: "RS" },
    "Bezerrão":                             { cidade: "Gama", estado: "Distrito Federal", uf: "DF" },
    "Bezerrão-DF":                          { cidade: "Gama", estado: "Distrito Federal", uf: "DF" },
    "Bezerrão-RN":                          { cidade: "Currais Novos", estado: "Rio Grande do Norte", uf: "RN" },
    "Boca do Lobo":                         { cidade: "Sede", estado: "Rio Grande do Sul", uf: "RS" },
    "Boleyn Ground":                        { cidade: "Grande Londres", pais: "Inglaterra", codigo: "gb" },
    "Boulanger Pucci":                      { cidade: "Uberaba", estado: "Minas Gerais", uf: "MG" },
    "Brinco de Ouro da Princesa":           { cidade: "Campinas", estado: "São Paulo", uf: "SP" },
    "Bruno José Daniel":                    { cidade: "Santo André", estado: "São Paulo", uf: "SP" },
    "Cachamay":                             { cidade: "Municipio Caroní", pais: "Venezuela", codigo: "ve" },
    "Camp Nou":                             { cidade: "Barcelona", pais: "Espanha", codigo: "es" },
    "Campo Público São Cristóvão":          { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Campo da Avenida Malaquias":           { cidade: "Recife", estado: "Pernambuco", uf: "PE" },
    "Campo da Companhia Agro Pastoril":     { cidade: "Belo Horizonte", estado: "Minas Gerais", uf: "MG" },
    "Campo da Consolação":                  { cidade: "São Paulo", estado: "São Paulo", uf: "SP" },
    "Campo da Floresta":                    { cidade: "São Paulo", estado: "São Paulo", uf: "SP" },
    "Campo da Graça":                       { cidade: "Salvador", estado: "Bahia", uf: "BA" },
    "Campo da Rua Carlos Seidl":            { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Campo do Americano":                   { cidade: "Campos dos Goytacazes", estado: "Rio de Janeiro", uf: "RJ" },
    "Campo do Barra Futebol Clube":         { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Campo do Cocotá":                      { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Campo do Jucutuquara":                 { cidade: "Vitória", estado: "Espírito Santo", uf: "ES" },
    "Campo do Kosmos":                      { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Campo do Rio Vermelho":                { cidade: "Salvador", estado: "Bahia", uf: "BA" },
    "Campo do Serrano":                     { cidade: "Petrópolis", estado: "Rio de Janeiro", uf: "RJ" },
    "Campos Sales":                         { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Campos Salles":                        { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Canarinho":                            { cidade: "Manaus", estado: "Amazonas", uf: "AM" },
    "Canindé":                              { cidade: "São Paulo", estado: "São Paulo", uf: "SP" },
    "Carlos Colnaghi":                      { cidade: "Capivari", estado: "São Paulo", uf: "SP" },
    "Carlos Guinle":                        { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Carlos Seidl":                         { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Casablanca":                           { cidade: "Cumbaya", pais: "Equador", codigo: "ec" },
    "Castelão-CE":                          { cidade: "Fortaleza", estado: "Ceará", uf: "CE" },
    "Castelão-MA":                          { cidade: "São Luís", estado: "Maranhão", uf: "MA" },
    "Centenario Ciudad de Quilmes":         { cidade: "Quilmes", pais: "Argentina", codigo: "ar" },
    "Centenário (Caxias do Sul)":           { cidade: "Caxias do Sul", estado: "Rio Grande do Sul", uf: "RS" },
    "Centenário (Machado)":                 { cidade: "Machado", estado: "Minas Gerais", uf: "MG" },
    "Centenário (Ubá)":                     { cidade: "Ubá", estado: "Minas Gerais", uf: "MG" },
    "Chamartín":                            { cidade: "Madrid", pais: "Espanha", codigo: "es" },
    "Charmilles":                           { cidade: "Lancy", pais: "Suíça", codigo: "ch" },
    "Chácara das Camélias":                 { cidade: "Porto Alegre", estado: "Rio Grande do Sul", uf: "RS" },
    "Cinco de Julho":                       { cidade: "Daïra de Chéraga", pais: "Argélia", codigo: "dz" },
    "Ciudad de La Plata":                   { cidade: "Los Hornos", pais: "Argentina", codigo: "ar" },
    "Colombes":                             { cidade: "Colombes", pais: "França", codigo: "fr" },
    "Colombino":                            { cidade: "Huelva", pais: "Espanha", codigo: "es" },
    "Colosso da Lagoa":                     { cidade: "Erechim", estado: "Santa Catarina", uf: "SC" },
    "Colosso dos Tapajós":                  { cidade: "Santarém", estado: "Pará", uf: "PA" },
    "Correão":                              { cidade: "Cabo Frio", estado: "Rio de Janeiro", uf: "RJ" },
    "Correão-PI":                           { cidade: "Teresina", estado: "Piauí", uf: "PI" },
    "Craven Cottage":                       { cidade: "Grande Londres", pais: "Inglaterra", codigo: "gb" },
    "Crystal Palace Training Ground":       { cidade: "Grande Londres", pais: "Inglaterra", codigo: "gb" },
    "Cícero de Souza Marques":              { cidade: "Bragança Paulista", estado: "São Paulo", uf: "SP" },
    "De Kuip":                              { cidade: "Roterdão", pais: "Holanda", codigo: "nl" },
    "Defensores Del Chaco":                 { cidade: "Assunção", pais: "Paraguai", codigo: "py" },
    "Duarte de Paiva":                      { cidade: "Sete Lagoas", estado: "Minas Gerais", uf: "MG" },
    "Dutrinha":                             { cidade: "Cuiabá", estado: "Mato Grosso", uf: "MT" },
    "Eduardo Guinle":                       { cidade: "Nova Friburgo", estado: "Rio de Janeiro", uf: "RJ" },
    "El Arcangel":                          { cidade: "Córdova", pais: "Espanha", codigo: "es" },
    "El Campín":                            { cidade: "Bogotá", pais: "Colômbia", codigo: "co" },
    "El Cilindro":                          { cidade: "Avellaneda", pais: "Argentina", codigo: "ar" },
    "El Molinón":                           { cidade: "Gijón / Xixón", pais: "Espanha", codigo: "es" },
    "El Teniente":                          { cidade: "Rancagua", pais: "Chile", codigo: "cl" },
    "Elland Road":                          { cidade: "Leeds", pais: "Inglaterra", codigo: "gb" },
    "Engenheiro Araripe":                   { cidade: "Cachoeiro de Itapemirim", estado: "Espírito Santo", uf: "ES" },
    "Engenho de Dentro":                    { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Ernestão":                             { cidade: "Joinville", estado: "Santa Catarina", uf: "SC" },
    "Ernst Happel Stadion":                 { cidade: "Viena", pais: "Áustria", codigo: "at" },
    "Esperança":                            { cidade: "Itajubá", estado: "São Paulo", uf: "SP" },
    "Esperidião Geraidine":                 { cidade: "Barra Mansa", estado: "Rio de Janeiro", uf: "RJ" },
    "Estadi de Sarriá":                     { cidade: "Barcelona", pais: "Espanha", codigo: "es" },
    "Estadio Uno":                          { cidade: "La Plata", pais: "Argentina", codigo: "ar" },
    "Estrada Dona Castorina":               { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Estrada do Norte":                     { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Estradinha":                           { cidade: "Paranaguá", estado: "Paraná", uf: "PR" },
    "Estrela d'Alva":                       { cidade: "Bagé", estado: "Rio Grande do Sul", uf: "RS" },
    "Estádio León":                         { cidade: "León", pais: "México", codigo: "mx" },
    "Estádio Municipal Geraldão":           { cidade: "Barreiras", estado: "Bahia", uf: "BA" },
    "Estádio Municipal Lúcio Pipino":       { cidade: "Umuarama", estado: "Paraná", uf: "PR" },
    "Estádio Municipal de Aracaju":         { cidade: "Aracaju", estado: "Sergipe", uf: "SE" },
    "Estádio Municipal de Diamantina":      { cidade: "Diamantina", estado: "Minas Gerais", uf: "MG" },
    "Estádio Municipal de Vassouras":       { cidade: "Vassouras", estado: "Rio de Janeiro", uf: "RJ" },
    "Estádio Nacional da Costa Rica":       { cidade: "San José", pais: "Costa Rica", codigo: "cr" },
    "Estádio Tecnológico":                  { cidade: "Monterrei", pais: "México", codigo: "mx" },
    "Estádio da Baixada":                   { cidade: "Curitiba", estado: "Paraná", uf: "PR" },
    "Estádio da Floresta":                  { cidade: "São Paulo", estado: "São Paulo", uf: "SP" },
    "Estádio da Luz":                       { cidade: "Lisboa", pais: "Portugal", codigo: "pt" },
    "Estádio da Mogiana":                   { cidade: "Campinas", estado: "São Paulo", uf: "SP" },
    "Estádio das Antas":                    { cidade: "Porto", pais: "Portugal", codigo: "pt" },
    "Estádio das Oliveiras":                { cidade: "Rio Grande", estado: "Rio Grande do Sul", uf: "RS" },
    "Estádio de Buenavista":                { cidade: "Oviedo", pais: "Espanha", codigo: "es" },
    "Estádio de La Condomina":              { cidade: "Múrcia", pais: "Espanha", codigo: "es" },
    "Estádio do Café":                      { cidade: "Londrina", estado: "Paraná", uf: "PR" },
    "Estádio do Mutange":                   { cidade: "Maceió", estado: "Alagoas", uf: "AL" },
    "Estádio dos Eucaliptos":               { cidade: "Bento Gonçalves", estado: "Rio Grande do Sul", uf: "RS" },
    "Estádio dos Eucaliptos (Santa Maria)": { cidade: "Santa Maria", estado: "Rio Grande do Sul", uf: "RS" },
    "Expedicionário":                       { cidade: "Macaé", estado: "Rio de Janeiro", uf: "RJ" },
    "Farião":                               { cidade: "Divinópolis", estado: "Minas Gerais", uf: "MG" },
    "Fazendinha":                           { cidade: "São Paulo", estado: "São Paulo", uf: "SP" },
    "Fello Meza":                           { cidade: "Oriental", pais: "Costa Rica", codigo: "cr" },
    "Figueira de Melo":                     { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Flor Branca":                          { cidade: "São Salvador", pais: "El Salvador", codigo: "sv" },
    "Florencio Sola":                       { cidade: "Remedios de Escalada", pais: "Argentina", codigo: "ar" },
    "Fonte Luminosa":                       { cidade: "Araraquara", estado: "São Paulo", uf: "SP" },
    "Frankenstadion":                       { cidade: "Nuremberga / Nurembergue", pais: "Alemanha", codigo: "de" },
    "Frasqueirão":                          { cidade: "Natal", estado: "Rio Grande do Norte", uf: "RN" },
    "Fratton Park":                         { cidade: "Portsmouth", pais: "Inglaterra", codigo: "gb" },
    "Félix Capriles":                       { cidade: "Cochabamba", pais: "Bolívia", codigo: "bo" },
    "Gammliavallen":                        { cidade: "Umeå", pais: "Suécia", codigo: "se" },
    "General Affonseca":                    { cidade: "Lorena", estado: "São Paulo", uf: "SP" },
    "General Pablo Rojas":                  { cidade: "Assunção", pais: "Paraguai", codigo: "py" },
    "General Rumiñahui":                    { cidade: "Sangolquí", pais: "Equador", codigo: "ec" },
    "Georg Melches":                        { cidade: "Essen", pais: "Alemanha", codigo: "de" },
    "George Capwell":                       { cidade: "Guayaquil", pais: "Equador", codigo: "ec" },
    "Germano Kruger":                       { cidade: "Ponta Grossa", estado: "Paraná", uf: "PR" },
    "Gerson Amaral":                        { cidade: "Coruripe", estado: "Alagoas", uf: "AL" },
    "Giulite Coutinho":                     { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Godofredo Cruz":                       { cidade: "Campos dos Goytacazes", estado: "Rio de Janeiro", uf: "RJ" },
    "Governador Bley":                      { cidade: "Vitória", estado: "Espírito Santo", uf: "ES" },
    "Gran Parque Central":                  { cidade: "Montevidéu", pais: "Uruguai", codigo: "uy" },
    "Gran Stadium Cerveza Tropical":        { cidade: "La Habana", pais: "Cuba", codigo: "cu" },
    "Griffin Park":                         { cidade: "Grande Londres", pais: "Inglaterra", codigo: "gb" },
    "Grêmio Fronteira":                     { cidade: "Araranguá", estado: "Santa Catarina", uf: "SC" },
    "Guanahyro Fraga Motta":                { cidade: "Leopoldina", estado: "Minas Gerais", uf: "MG" },
    "Gumercindo Rodrigues Neves":           { cidade: "Campo Belo", estado: "Minas Gerais", uf: "MG" },
    "Hanói Stadium":                        { cidade: "Hanói", pais: "Vietnã", codigo: "vn" },
    "Hardturm":                             { cidade: "Zurique", pais: "Suíça", codigo: "ch" },
    "Heitor Bravo":                         { cidade: "Saquarema", estado: "Rio de Janeiro", uf: "RJ" },
    "Heriberto Hulse":                      { cidade: "Criciúma", estado: "Santa Catarina", uf: "SC" },
    "Hermenegildo Barcelos":                { cidade: "Arraial do Cabo", estado: "Rio de Janeiro", uf: "RJ" },
    "Hernando Siles":                       { cidade: "La Paz", pais: "Bolívia", codigo: "bo" },
    "Home Park":                            { cidade: "Plymouth", pais: "Inglaterra", codigo: "gb" },
    "Houphouet Boigny":                     { cidade: "Abidjã", pais: "Costa do Marfim", codigo: "ci" },
    "Inca Garcilaso de La Vega":            { cidade: "Cusco", pais: "Peru", codigo: "pe" },
    "Independence Park":                    { cidade: "Kingston", pais: "Jamaica", codigo: "jm" },
    "Ipatingão":                            { cidade: "Ipatinga", estado: "Minas Gerais", uf: "MG" },
    "Israel Pinheiro (Brasília)":           { cidade: "Guará", estado: "Distrito Federal", uf: "DF" },
    "Israel Pinheiro (Itabira)":            { cidade: "Itabira", estado: "Minas Gerais", uf: "MG" },
    "Itabunão":                             { cidade: "Itabuna", estado: "Bahia", uf: "BA" },
    "Jair Bittencourt":                     { cidade: "Itaperuna", estado: "Rio de Janeiro", uf: "RJ" },
    "Jalisco":                              { cidade: "Guadalajara", pais: "México", codigo: "mx" },
    "Jayme Cintra":                         { cidade: "Jundiaí", estado: "São Paulo", uf: "SP" },
    "Joaquim Portugal":                     { cidade: "São João del-Rei", estado: "Minas Gerais", uf: "MG" },
    "Joaquim de Paula Xavier":              { cidade: "Ponta Grossa", estado: "Paraná", uf: "PR" },
    "Joia da Princesa":                     { cidade: "Feira de Santana", estado: "Bahia", uf: "BA" },
    "Jonas Duarte":                         { cidade: "Anápolis", estado: "Goiás", uf: "GO" },
    "José Fragelli":                        { cidade: "Cuiabá", estado: "Mato Grosso", uf: "MT" },
    "José Liberatti":                       { cidade: "Itápolis", estado: "São Paulo", uf: "SP" },
    "José Paiz Soares":                     { cidade: "Juiz de Fora", estado: "Minas Gerais", uf: "MG" },
    "Joviniano Dourado Lopes":              { cidade: "Irecê", estado: "Bahia", uf: "BA" },
    "Juca Ribeiro":                         { cidade: "Uberlândia", estado: "Minas Gerais", uf: "MG" },
    "Juscelino Kubitschek-GO":              { cidade: "Itumbiara", estado: "Goiás", uf: "GO" },
    "Juscelino Kubitschek-MG":              { cidade: "Belo Horizonte", estado: "Minas Gerais", uf: "MG" },
    "Justiniano de Melo e Silva":           { cidade: "Colatina", estado: "Espírito Santo", uf: "ES" },
    "Juvenal Lamartine":                    { cidade: "Natal", estado: "Rio Grande do Norte", uf: "RN" },
    "Kobe Universiade Memorial":            { cidade: "Kobe", pais: "Japão", codigo: "jp" },
    "La Beaujoire":                         { cidade: "Nantes", pais: "França", codigo: "fr" },
    "La Doble Visera":                      { cidade: "Avellaneda", pais: "Argentina", codigo: "ar" },
    "La Huerta":                            { cidade: "Assunção", pais: "Paraguai", codigo: "py" },
    "La Rosaleda":                          { cidade: "Málaga", pais: "Espanha", codigo: "es" },
    "Lacerdão":                             { cidade: "Caruaru", estado: "Pernambuco", uf: "PE" },
    "Les Corts":                            { cidade: "Barcelona", pais: "Espanha", codigo: "es" },
    "Limeirão":                             { cidade: "Limeira", estado: "São Paulo", uf: "SP" },
    "Lincoln Financial Field":              { cidade: "Filadélfia", pais: "Estados Unidos", codigo: "us" },
    "Lindolfo Monteiro":                    { cidade: "Teresina", estado: "Piauí", uf: "PI" },
    "London Road":                          { cidade: "Peterborough", pais: "Inglaterra", codigo: "gb" },
    "Los Angeles Memorial Coliseum":        { cidade: "Los Angeles", pais: "Estados Unidos", codigo: "us" },
    "Los Larios":                           { cidade: "Xerém", estado: "Rio de Janeiro", uf: "RJ" },
    "Lourdes":                              { cidade: "Belo Horizonte", estado: "Minas Gerais", uf: "MG" },
    "Louzadão":                             { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Ludwigspark Stadion":                  { cidade: "Sarbruque", pais: "Alemanha", codigo: "de" },
    "Luis Afonso Giagni":                   { cidade: "Luque", pais: "Paraguai", codigo: "py" },
    "Luis Pirata Fuente":                   { cidade: "Valente Díaz", pais: "México", codigo: "mx" },
    "Lumen Field":                          { cidade: "Seattle", pais: "Estados Unidos", codigo: "us" },
    "Luís Sitjar":                          { cidade: "Palma", pais: "Espanha", codigo: "es" },
    "Machadão":                             { cidade: "Natal", estado: "Rio Grande do Norte", uf: "RN" },
    "Maião":                                { cidade: "Mirassol", estado: "São Paulo", uf: "SP" },
    "Malmo Stadion":                        { cidade: "Malmo", pais: "Suécia", codigo: "se" },
    "Mamudão":                              { cidade: "Governador Valadares", estado: "Minas Gerais", uf: "MG" },
    "Manduzão":                             { cidade: "Pouso Alegre", estado: "Minas Gerais", uf: "MG" },
    "Mangueirão":                           { cidade: "Belém", estado: "Pará", uf: "PA" },
    "Mansiche":                             { cidade: "Trujillo", pais: "Peru", codigo: "pe" },
    "Marechal Hermes":                      { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Martins Pereira":                      { cidade: "São José dos Campos", estado: "São Paulo", uf: "SP" },
    "Mauritsstadion":                       { cidade: "Geleen", pais: "Holanda", codigo: "nl" },
    "Melão":                                { cidade: "Varginha", estado: "Minas Gerais", uf: "MG" },
    "Mestalla":                             { cidade: "Valência", pais: "Espanha", codigo: "es" },
    "Metropolitano":                        { cidade: "Madrid", pais: "Espanha", codigo: "es" },
    "Metropolitano Roberto Meléndez":       { cidade: "Perímetro Urbano Barranquilla", pais: "Colômbia", codigo: "co" },
    "Misael Delgado":                       { cidade: "San Diego", pais: "Venezuela", codigo: "ve" },
    "Mithatpasa":                           { cidade: "Esmirna", pais: "Turquia", codigo: "tr" },
    "Moacyrzão":                            { cidade: "Macaé", estado: "Rio de Janeiro", uf: "RJ" },
    "Mohammed V":                           { cidade: "Casablanca", pais: "Marrocos", codigo: "ma" },
    "Moisés Lucarelli":                     { cidade: "Campinas", estado: "São Paulo", uf: "SP" },
    "Monumental Banco Pichincha":           { cidade: "Guaiaquil", pais: "Equador", codigo: "ec" },
    "Monumental David Arellano":            { cidade: "Santiago", pais: "Chile", codigo: "cl" },
    "Monumental U":                         { cidade: "Lurigancho", pais: "Peru", codigo: "pe" },
    "Monumental do Sesi":                   { cidade: "Blumenau", estado: "Santa Catarina", uf: "SC" },
    "Moraes e Silva":                       { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Morenão":                              { cidade: "Campo Grande", estado: "Mato Grosso do Sul", uf: "MS" },
    "Munsu Stadium":                        { cidade: "Ulsan", pais: "Coreia do Sul", codigo: "kr" },
    "Mário Alves Mendonça":                 { cidade: "São José do Rio Preto", estado: "São Paulo", uf: "SP" },
    "Nacional (Lima)":                      { cidade: "Lima", pais: "Peru", codigo: "pe" },
    "Nacional (Tóquio)":                    { cidade: "Shinjuku", pais: "Japão", codigo: "jp" },
    "Nacional Brígido Iriarte":             { cidade: "Caracas", pais: "Venezuela", codigo: "ve" },
    "Nacional de Chile":                    { cidade: "Santiago", pais: "Chile", codigo: "cl" },
    "Nacional de Dakar":                    { cidade: "Dacar", pais: "Senegal", codigo: "sn" },
    "Nacional de Oran":                     { cidade: "Orã", pais: "Argélia", codigo: "dz" },
    "Nagai Stadium":                        { cidade: "Osaka", pais: "Japão", codigo: "jp" },
    "Nassri Mattar":                        { cidade: "Teófilo Otoni", estado: "Minas Gerais", uf: "MG" },
    "Nep Stadium":                          { cidade: "Budapeste", pais: "Hungria", codigo: "hu" },
    "Nhozinho Santos":                      { cidade: "São Luís", estado: "Maranhão", uf: "MA" },
    "Nildo Pereira de Menezes":             { cidade: "Serra Talhada", estado: "Pernambuco", uf: "PE" },
    "Ninian Park":                          { cidade: "Cardiff", pais: "Inglaterra", codigo: "gb" },
    "Norberto Tito Tomaghello":             { cidade: "San Juan Bautista", pais: "Argentina", codigo: "ar" },
    "Nuevo Gasometro":                      { cidade: "Buenos Aires", pais: "Argentina", codigo: "ar" },
    "Népstadion":                           { cidade: "Budapeste", pais: "Hungria", codigo: "hu" },
    "OBA":                                  { cidade: "Goiânia", estado: "Goiás", uf: "GO" },
    "Odair Gama":                           { cidade: "Três Rios", estado: "Rio de Janeiro", uf: "RJ" },
    "Olímpico (Goiânia)":                   { cidade: "Goiânia", estado: "Goiás", uf: "GO" },
    "Olímpico Atahualpa":                   { cidade: "Distrito Metropolitano de Quito", pais: "Equador", codigo: "ec" },
    "Olímpico Universitario":               { cidade: "Cidade do México", pais: "México", codigo: "mx" },
    "Olímpico de Amsterdam":                { cidade: "Amsterdã", pais: "Holanda", codigo: "nl" },
    "Olímpico de Amsterdã":                 { cidade: "Amsterdã", pais: "Holanda", codigo: "nl" },
    "Olímpico de Caracas":                  { cidade: "Caracas", pais: "Venezuela", codigo: "ve" },
    "Olímpico de Roma":                     { cidade: "Roma", pais: "Itália", codigo: "it" },
    "Olímpico-RS":                          { cidade: "Porto Alegre", estado: "Rio Grande do Sul", uf: "RS" },
    "Omiya":                                { cidade: "Saitama", pais: "Japão", codigo: "jp" },
    "Orlando Mattos":                       { cidade: "Paranaguá", estado: "Paraná", uf: "PR" },
    "Orlando Scarpelli":                    { cidade: "Florianópolis", estado: "Santa Catarina", uf: "SC" },
    "Otacílio Negrão de Lima":              { cidade: "Belo Horizonte", estado: "Minas Gerais", uf: "MG" },
    "Palestra Itália":                      { cidade: "São Paulo", estado: "São Paulo", uf: "SP" },
    "Palma Travassos":                      { cidade: "Ribeirão Preto", estado: "São Paulo", uf: "SP" },
    "Parc Astrid":                          { cidade: "Anderlecht", pais: "Bélgica", codigo: "be" },
    "Parc Des Princes":                     { cidade: "Paris", pais: "França", codigo: "fr" },
    "Parque Asturias":                      { cidade: "Cidade do México", pais: "México", codigo: "mx" },
    "Parque da Graciosa":                   { cidade: "Curitiba", estado: "Paraná", uf: "PR" },
    "Pascual Guerrero":                     { cidade: "Cáli", pais: "Colômbia", codigo: "co" },
    "Passo das Emas":                       { cidade: "Lucas do Rio Verde", estado: "Mato Grosso", uf: "MT" },
    "Paulo Fernandes":                      { cidade: "Barra do Piraí", estado: "Rio de Janeiro", uf: "RJ" },
    "Pelezão":                              { cidade: "Guará", estado: "Distrito Federal", uf: "DF" },
    "Petrônio Portela":                     { cidade: "Teresina", estado: "Piauí", uf: "PI" },
    "Pinheirão":                            { cidade: "Curitiba", estado: "Paraná", uf: "PR" },
    "Pituaçu":                              { cidade: "Salvador", estado: "Bahia", uf: "BA" },
    "Playa Ancha":                          { cidade: "Valparaíso", pais: "Chile", codigo: "cl" },
    "Plínio Lemos":                         { cidade: "Campina Grande", estado: "Paraíba", uf: "PB" },
    "Prado Mineiro":                        { cidade: "Belo Horizonte", estado: "Minas Gerais", uf: "MG" },
    "Praia Vermelha":                       { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Presbítero Bartolomé Grella":          { cidade: "Paraná", pais: "Argentina", codigo: "ar" },
    "Presidente Vargas":                    { cidade: "Fortaleza", estado: "Ceará", uf: "CE" },
    "Presidente Vargas (Campina Grande)":   { cidade: "Campina Grande", estado: "Paraíba", uf: "PB" },
    "Prince Abdullah al-Faisal":            { cidade: "Meca", pais: "Arábia Saudita", codigo: "sa" },
    "Prudentão":                            { cidade: "Presidente Prudente", estado: "São Paulo", uf: "SP" },
    "Puerto Sajonia":                       { cidade: "Assunção", pais: "Paraguai", codigo: "py" },
    "Raiz da Serra":                        { cidade: "Inhomirim", estado: "Rio de Janeiro", uf: "RJ" },
    "Ramón de Carranza":                    { cidade: "Cádis", pais: "Espanha", codigo: "es" },
    "Rasunda":                              { cidade: "Solna", pais: "Suécia", codigo: "se" },
    "Raul Sertã":                           { cidade: "Nova Friburgo", estado: "Rio de Janeiro", uf: "RJ" },
    "Rei Pelé":                             { cidade: "Maceió", estado: "Alagoas", uf: "AL" },
    "Ressacada":                            { cidade: "Florianópolis", estado: "Santa Catarina", uf: "SC" },
    "Riazor":                               { cidade: "A Corunha", pais: "Espanha", codigo: "es" },
    "Ricardo Saprissa":                     { cidade: "San José", pais: "Costa Rica", codigo: "cr" },
    "Rodríguez López":                      { cidade: "Santa Cruz de Tenerife", pais: "Espanha", codigo: "es" },
    "Romeirão":                             { cidade: "Juazeiro do Norte", estado: "Ceará", uf: "CE" },
    "Ronaldão":                             { cidade: "Poços de Caldas", estado: "Minas Gerais", uf: "MG" },
    "Rose Bowl":                            { cidade: "Pasadena", pais: "Estados Unidos", codigo: "us" },
    "Rua Bariri":                           { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Constituição":                     { cidade: "Niterói", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Cândido Silva":                    { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Desembargador Isidro":             { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Domingos Lopes":                   { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Doutor March":                     { cidade: "Niterói", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Dr. Paulo Cézar":                  { cidade: "Niterói", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Ferrer":                           { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua General Silva Teles":              { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Javari":                           { cidade: "São Paulo", estado: "São Paulo", uf: "SP" },
    "Rua João Pinheiro":                    { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Magalhães Castro":                 { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Paysandu":                         { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua São Clemente":                     { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua São Lourenço":                     { cidade: "Niterói", estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Tibiriçá":                         { cidade: "Ribeirão Preto", estado: "São Paulo", uf: "SP" },
    "Rubens Gomes":                         { cidade: "Vila Velha", estado: "Espírito Santo", uf: "ES" },
    "Salles Oliveira":                      { cidade: "Juiz de Fora", estado: "Minas Gerais", uf: "MG" },
    "San Carlos de Apoquindo":              { cidade: "Santiago", pais: "Chile", codigo: "cl" },
    "San Nanes":                            { cidade: "Bilbau", pais: "Espanha", codigo: "es" },
    "San Paolo":                            { cidade: "Nápoles", pais: "Itália", codigo: "it" },
    "San Siro":                             { cidade: "Milão", pais: "Itália", codigo: "it" },
    "Santa Cruz":                           { cidade: "Ribeirão Preto", estado: "São Paulo", uf: "SP" },
    "Santa Laura":                          { cidade: "Santiago", pais: "Chile", codigo: "cl" },
    "Santa Tereza":                         { cidade: "Barbacena", estado: "Minas Gerais", uf: "MG" },
    "Sausalito":                            { cidade: "Viña del Mar", pais: "Chile", codigo: "cl" },
    "Sebastião César da Silva":             { cidade: "Araguari", estado: "Minas Gerais", uf: "MG" },
    "Selhurst Park":                        { cidade: "Grande Londres", pais: "Inglaterra", codigo: "gb" },
    "Serejão":                              { cidade: "Ceilândia", estado: "Distrito Federal", uf: "DF" },
    "Serra Dourada":                        { cidade: "Goiânia", estado: "Goiás", uf: "GO" },
    "Serrinha":                             { cidade: "Goiânia", estado: "Goiás", uf: "GO" },
    "Stade Auguste Delaune":                { cidade: "Reims", pais: "França", codigo: "fr" },
    "Stade Félix Bollaert":                 { cidade: "Lens", pais: "França", codigo: "fr" },
    "Stade Jules Deschaseaux":              { cidade: "Le Havre", pais: "França", codigo: "fr" },
    "Stade de Venoix":                      { cidade: "Caen", pais: "França", codigo: "fr" },
    "Stade de l'Aube":                      { cidade: "Saint-Parres-aux-Tertres", pais: "França", codigo: "fr" },
    "Stadio Comunale":                      { cidade: "Florença", pais: "Itália", codigo: "it" },
    "Stadio Olimpico Grande Torino":        { cidade: "Turim", pais: "Itália", codigo: "it" },
    "Stadion Slavia":                       { cidade: "Praga", pais: "República Tcheca", codigo: "cz" },
    "Stadium 974":                          { cidade: "Doha", pais: "Catar", codigo: "qa" },
    "Stadium Nord":                         { cidade: "Villeneuve-d'Ascq", pais: "França", codigo: "fr" },
    "Stará střelnice":                      { cidade: "Brno", pais: "República Tcheca", codigo: "cz" },
    "Strahov":                              { cidade: "Praga", pais: "República Tcheca", codigo: "cz" },
    "Sumaré":                               { cidade: "Cachoeiro de Itapemirim", estado: "Espírito Santo", uf: "ES" },
    "Tehelné Pole":                         { cidade: "Bratislava", pais: "Eslováquia", codigo: "sk" },
    "Teixeira de Castro":                   { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Tiezão":                               { cidade: "Três Rios", estado: "Rio de Janeiro", uf: "RJ" },
    "Tupy Cantanhede":                      { cidade: "Parintins", estado: "Pará", uf: "PA" },
    "Turf Moor":                            { cidade: "Burnley", pais: "Inglaterra", codigo: "gb" },
    "Tóquio Dome Stadium":                  { cidade: "Tóquio", pais: "Japão", codigo: "jp" },
    "Uberabão":                             { cidade: "Uberaba", estado: "Minas Gerais", uf: "MG" },
    "Ullevi":                               { cidade: "Gotemburgo", pais: "Suécia", codigo: "se" },
    "Ulrico Mursa":                         { cidade: "Santos", estado: "São Paulo", uf: "SP" },
    "Universitário de Caracas":             { cidade: "Caracas", pais: "Venezuela", codigo: "ve" },
    "VGD":                                  { cidade: "Londrina", estado: "Paraná", uf: "PR" },
    "Vail Chaves":                          { cidade: "Mogi Mirim", estado: "São Paulo", uf: "SP" },
    "Verdão":                               { cidade: "Cuiabá", estado: "Mato Grosso", uf: "MT" },
    "Viejo Gasometro":                      { cidade: "Buenos Aires", pais: "Argentina", codigo: "ar" },
    "Vila Capanema":                        { cidade: "Curitiba", estado: "Paraná", uf: "PR" },
    "Vila Olímpica Parahyba":               { cidade: "João Pessoa", estado: "Paraíba", uf: "PB" },
    "Vivaldão":                             { cidade: "Manaus", estado: "Amazonas", uf: "AM" },
    "Voluntários da Pátria":                { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
    "Víctor Agustín Ugarte":                { cidade: "Municipio Sucre", pais: "Bolívia", codigo: "bo" },
    "Waldermar de Brito":                   { cidade: "Criciúma", estado: "Santa Catarina", uf: "SC" },
    "Waldomirão":                           { cidade: "Jequié", estado: "Bahia", uf: "BA" },
    "Wankdorf Stadium":                     { cidade: "Berna", pais: "Suíça", codigo: "ch" },
    "Wildparkstadion":                      { cidade: "Karlsruhe", pais: "Alemanha", codigo: "de" },
    "Zenor Pedrosa Rocha":                  { cidade: "Nova Venécia", estado: "Espírito Santo", uf: "ES" },
    "Zequinha Roriz":                       { cidade: "Luziânia", estado: "Goiás", uf: "GO" },
    "Ítalo del Cima":                       { cidade: "Rio de Janeiro", estado: "Rio de Janeiro", uf: "RJ" },
};

export default estadiosLocais;
