const estados = {
    "Americano":           { estado: "Rio de Janeiro",       uf: "RJ" },
    "América-MG":          { estado: "Minas Gerais",         uf: "MG" },
    "Athletico-PR":        { estado: "Paraná",               uf: "PR" },
    "Atlético-GO":         { estado: "Goiás",                uf: "GO" },
    "Atlético-MG":         { estado: "Minas Gerais",         uf: "MG" },
    "Atlético-PR":         { estado: "Paraná",               uf: "PR" },
    "Audax Rio":           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Avaí":                { estado: "Santa Catarina",       uf: "SC" },
    "Bahia":               { estado: "Bahia",                uf: "BA" },
    "Bangu":               { estado: "Rio de Janeiro",       uf: "RJ" },
    "Boa Esporte":         { estado: "Minas Gerais",         uf: "MG" },
    "Boavista":            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Bonsucesso":          { estado: "Rio de Janeiro",       uf: "RJ" },
    "Bragantino":          { estado: "São Paulo",            uf: "SP" },
    "Brusque":             { estado: "Santa Catarina",       uf: "SC" },
    "CRB":                 { estado: "Alagoas",              uf: "AL" },
    "CSA":                 { estado: "Alagoas",              uf: "AL" },
    "Capital":             { estado: "Distrito Federal",     uf: "DF" },
    "Ceilândia":           { estado: "Distrito Federal",     uf: "DF" },
    "Chapecoense":         { estado: "Santa Catarina",       uf: "SC" },
    "Confiança":           { estado: "Sergipe",              uf: "SE" },
    "Corinthians":         { estado: "São Paulo",            uf: "SP" },
    "Coritiba":            { estado: "Paraná",               uf: "PR" },
    "Criciúma":            { estado: "Santa Catarina",       uf: "SC" },
    "Cruzeiro":            { estado: "Minas Gerais",         uf: "MG" },
    "Cuiabá":              { estado: "Mato Grosso",         uf: "MT" },
    "Figueirense":         { estado: "Santa Catarina",       uf: "SC" },
    "Flamengo":            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Fluminense":          { estado: "Rio de Janeiro",       uf: "RJ" },
    "Ceará":               { estado: "Ceará",                uf: "CE" },
    "Fortaleza":           { estado: "Ceará",                uf: "CE" },
    "Goiás":               { estado: "Goiás",                uf: "GO" },
    "Grêmio":              { estado: "Rio Grande do Sul",    uf: "RS" },
    "Guarani":             { estado: "São Paulo",            uf: "SP" },
    "Internacional":       { estado: "Rio Grande do Sul",    uf: "RS" },
    "Juventude":           { estado: "Rio Grande do Sul",    uf: "RS" },
    "Macaé":               { estado: "Rio de Janeiro",       uf: "RJ" },
    "Madureira":           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Maricá":              { estado: "Rio de Janeiro",       uf: "RJ" },
    "Mirassol":            { estado: "São Paulo",            uf: "SP" },
    "Mogi Mirim":          { estado: "São Paulo",            uf: "SP" },
    "Nova Iguaçu":         { estado: "Rio de Janeiro",       uf: "RJ" },
    "Novorizontino":       { estado: "São Paulo",            uf: "SP" },
    "Náutico":             { estado: "Pernambuco",           uf: "PE" },
    "Operário-PR":         { estado: "Paraná",               uf: "PR" },
    "Palmeiras":           { estado: "São Paulo",            uf: "SP" },
    "Paraná":              { estado: "Paraná",               uf: "PR" },
    "Paysandu":            { estado: "Pará",                 uf: "PA" },
    "Ponte Preta":         { estado: "São Paulo",            uf: "SP" },
    "Portuguesa-RJ":       { estado: "Rio de Janeiro",       uf: "RJ" },
    "Red Bull Bragantino": { estado: "São Paulo",            uf: "SP" },
    "Remo":                { estado: "Pará",                 uf: "PA" },
    "Resende":             { estado: "Rio de Janeiro",       uf: "RJ" },
    "Sampaio Corrêa":      { estado: "Maranhão",             uf: "MA" },
    "Sampaio Corrêa-RJ":   { estado: "Rio de Janeiro",       uf: "RJ" },
    "Santa Cruz":          { estado: "Pernambuco",           uf: "PE" },
    "Santos":              { estado: "São Paulo",            uf: "SP" },
    "Sport":               { estado: "Pernambuco",           uf: "PE" },
    "São Caetano":         { estado: "São Paulo",            uf: "SP" },
    "São Paulo":           { estado: "São Paulo",            uf: "SP" },
    "Taubaté":             { estado: "São Paulo",            uf: "SP" },
    "Vasco":               { estado: "Rio de Janeiro",       uf: "RJ" },
    "Vitória":             { estado: "Bahia",                uf: "BA" },
    "Volta Redonda":       { estado: "Rio de Janeiro",       uf: "RJ" },
    "Ypiranga":            { estado: "Rio Grande do Sul",    uf: "RS" },
};

export default estados;
