// estadios brasileiros: { estado, uf }
// estadios internacionais: { pais, codigo } (codigo = ISO 2 letras para flag-icons)

const estadiosLocais = {
    "Allianz Parque":          { estado: "São Paulo",          uf: "SP" },
    "Arena Condá":             { estado: "Santa Catarina",     uf: "SC" },
    "Arena MRV":               { estado: "Minas Gerais",       uf: "MG" },
    "Arena da Baixada":        { estado: "Paraná",             uf: "PR" },
    "Arena do Grêmio":         { estado: "Rio Grande do Sul",  uf: "RS" },
    "Barradão":                { estado: "Bahia",              uf: "BA" },
    "Caio Martins":            { estado: "Rio de Janeiro",     uf: "RJ" },
    "Centenario-URU":          { pais: "Uruguai",              codigo: "uy" },
    "Conselheiro Galvão":      { estado: "Rio de Janeiro",     uf: "RJ" },
    "Couto Pereira":           { estado: "Paraná",             uf: "PR" },
    "Elcyr Resende":           { estado: "Rio de Janeiro",     uf: "RJ" },
    "Independência":           { estado: "Minas Gerais",       uf: "MG" },
    "Jair Toscano":            { estado: "Rio de Janeiro",     uf: "RJ" },
    "Joaquim de Morais Filho": { estado: "São Paulo",          uf: "SP" },
    "Kleber Andrade":          { estado: "Espírito Santo",     uf: "ES" },
    "Lourivaldão":             { estado: "Rio de Janeiro",     uf: "RJ" },
    "Luso Brasileiro":         { estado: "Rio de Janeiro",     uf: "RJ" },
    "Maracanã":                { estado: "Rio de Janeiro",     uf: "RJ" },
    "Mineirão":                { estado: "Minas Gerais",       uf: "MG" },
    "Monumental de Núñez":     { pais: "Argentina",            codigo: "ar" },
    "Morumbi":                 { estado: "São Paulo",          uf: "SP" },
    "Moça Bonita":             { estado: "Rio de Janeiro",     uf: "RJ" },
    "Mário Helênio":           { estado: "Minas Gerais",       uf: "MG" },
    "Nabi Abi Chedid":         { estado: "São Paulo",          uf: "SP" },
    "Neo Química Arena":       { estado: "São Paulo",          uf: "SP" },
    "Nilton Santos":           { estado: "Rio de Janeiro",     uf: "RJ" },
    "Raulino de Oliveira":     { estado: "Rio de Janeiro",     uf: "RJ" },
    "São Januário":            { estado: "Rio de Janeiro",     uf: "RJ" },
    "Vila Belmiro":            { estado: "São Paulo",          uf: "SP" },

    // --- adicionados: estados/paises para estadios que ja tinham coordenadas ---
    "Fonte Nova": { estado: "Bahia", uf: "BA" },
    "General Severiano": { estado: "Rio de Janeiro", uf: "RJ" },
    "Gávea": { estado: "Rio de Janeiro", uf: "RJ" },
    "Ilha do Retiro": { estado: "Pernambuco", uf: "PE" },
    "Laranjeiras": { estado: "Rio de Janeiro", uf: "RJ" },
    "Mané Garrincha": { estado: "Distrito Federal", uf: "DF" },
    "Pacaembu": { estado: "São Paulo", uf: "SP" },
    "Acúrcio Torres": { estado: "Rio de Janeiro", uf: "RJ" },
    "Adautão": { estado: "Bahia", uf: "BA" },
    "Adolfo Konder": { estado: "Santa Catarina", uf: "SC" },
    "Aflitos": { estado: "Pernambuco", uf: "PE" },
    "Afonso de Carvalho": { estado: "Minas Gerais", uf: "MG" },
    "Alania": { pais: "Rússia", codigo: "ru" },
    "Albertão": { estado: "Piauí", uf: "PI" },
    "Alejandro Villanueva": { pais: "Peru", codigo: "pe" },
    "Alfredo Jaconi": { estado: "Rio Grande do Sul", uf: "RS" },
    "Alfredão": { estado: "São Paulo", uf: "SP" },
    "Almeidão": { estado: "Paraíba", uf: "PB" },
    "Aluizão": { estado: "Rondônia", uf: "RO" },
    "Amaro Lanari Júnior": { estado: "Minas Gerais", uf: "MG" },
    "Amigão": { estado: "Paraíba", uf: "PB" },
    "Anacleto Campanella": { estado: "São Paulo", uf: "SP" },
    "Annibal Batista de Toledo": { estado: "Goiás", uf: "GO" },
    "Antonio Accioly": { estado: "Goiás", uf: "GO" },
    "Arena Acreana": { estado: "Acre", uf: "AC" },
    "Arena Barueri": { estado: "São Paulo", uf: "SP" },
    "Arena Pantanal": { estado: "Mato Grosso", uf: "MT" },
    "Arena da Amazônia": { estado: "Amazonas", uf: "AM" },
    "Arena de Pernambuco": { estado: "Pernambuco", uf: "PE" },
    "Arena do Jacaré": { estado: "Minas Gerais", uf: "MG" },
    "Arruda": { estado: "Pernambuco", uf: "PE" },
    "Artemio Franchi": { pais: "Itália", codigo: "it" },
    "Arthur Marinho": { estado: "Mato Grosso do Sul", uf: "MS" },
    "Aryzão": { estado: "Rio de Janeiro", uf: "RJ" },
    "Atanasio Girardot": { pais: "Colômbia", codigo: "co" },
    "Atilio Marotti": { estado: "Rio de Janeiro", uf: "RJ" },
    "Augustinho Lima": { estado: "Distrito Federal", uf: "DF" },
    "Augusto Bauer": { estado: "Santa Catarina", uf: "SC" },
    "Augusto Simões Lopes": { estado: "Rio Grande do Sul", uf: "RS" },
    "Avenida Araguaya": { estado: "Minas Gerais", uf: "MG" },
    "Azteca": { pais: "México", codigo: "mx" },
    "Baenão": { estado: "Pará", uf: "PA" },
    "Baixada da Água Verde": { estado: "Paraná", uf: "PR" },
    "Balaídos": { pais: "Espanha", codigo: "es" },
    "Barão de São Francisco Filho": { estado: "Rio de Janeiro", uf: "RJ" },
    "Batistão": { estado: "Sergipe", uf: "SE" },
    "Beira-Rio": { estado: "Rio Grande do Sul", uf: "RS" },
    "Benedito Teixeira": { estado: "São Paulo", uf: "SP" },
    "Bento de Abreu": { estado: "São Paulo", uf: "SP" },
    "Bento de Freitas": { estado: "Rio Grande do Sul", uf: "RS" },
    "Bezerrão": { estado: "Distrito Federal", uf: "DF" },
    "Bezerrão-DF": { estado: "Distrito Federal", uf: "DF" },
    "Bezerrão-RN": { estado: "Rio Grande do Norte", uf: "RN" },
    "Boca do Lobo": { estado: "Rio Grande do Sul", uf: "RS" },
    "Boleyn Ground": { pais: "Inglaterra", codigo: "gb" },
    "Boulanger Pucci": { estado: "Minas Gerais", uf: "MG" },
    "Brinco de Ouro da Princesa": { estado: "São Paulo", uf: "SP" },
    "Bruno José Daniel": { estado: "São Paulo", uf: "SP" },
    "Cachamay": { pais: "Venezuela", codigo: "ve" },
    "Camp Nou": { pais: "Espanha", codigo: "es" },
    "Campo Público São Cristóvão": { estado: "Rio de Janeiro", uf: "RJ" },
    "Campo da Avenida Malaquias": { estado: "Pernambuco", uf: "PE" },
    "Campo da Companhia Agro Pastoril": { estado: "Minas Gerais", uf: "MG" },
    "Campo da Consolação": { estado: "São Paulo", uf: "SP" },
    "Campo da Floresta": { estado: "São Paulo", uf: "SP" },
    "Campo da Graça": { estado: "Bahia", uf: "BA" },
    "Campo da Rua Carlos Seidl": { estado: "Rio de Janeiro", uf: "RJ" },
    "Campo do Americano": { estado: "Rio de Janeiro", uf: "RJ" },
    "Campo do Barra Futebol Clube": { estado: "Rio de Janeiro", uf: "RJ" },
    "Campo do Cocotá": { estado: "Rio de Janeiro", uf: "RJ" },
    "Campo do Jucutuquara": { estado: "Espírito Santo", uf: "ES" },
    "Campo do Kosmos": { estado: "Rio de Janeiro", uf: "RJ" },
    "Campo do Rio Vermelho": { estado: "Bahia", uf: "BA" },
    "Campo do Serrano": { estado: "Rio de Janeiro", uf: "RJ" },
    "Campos Sales": { estado: "Rio de Janeiro", uf: "RJ" },
    "Campos Salles": { estado: "Rio de Janeiro", uf: "RJ" },
    "Canarinho": { estado: "Amazonas", uf: "AM" },
    "Canindé": { estado: "São Paulo", uf: "SP" },
    "Carlos Colnaghi": { estado: "São Paulo", uf: "SP" },
    "Carlos Guinle": { estado: "Rio de Janeiro", uf: "RJ" },
    "Carlos Seidl": { estado: "Rio de Janeiro", uf: "RJ" },
    "Casablanca": { pais: "Equador", codigo: "ec" },
    "Castelão-CE": { estado: "Ceará", uf: "CE" },
    "Castelão-MA": { estado: "Maranhão", uf: "MA" },
    "Centenario Ciudad de Quilmes": { pais: "Argentina", codigo: "ar" },
    "Centenário (Caxias do Sul)": { estado: "Rio Grande do Sul", uf: "RS" },
    "Centenário (Machado)": { estado: "Minas Gerais", uf: "MG" },
    "Centenário (Ubá)": { estado: "Minas Gerais", uf: "MG" },
    "Chamartín": { pais: "Espanha", codigo: "es" },
    "Charmilles": { pais: "Suíça", codigo: "ch" },
    "Chácara das Camélias": { estado: "Rio Grande do Sul", uf: "RS" },
    "Cinco de Julho": { pais: "Argélia", codigo: "dz" },
    "Ciudad de La Plata": { pais: "Argentina", codigo: "ar" },
    "Colombes": { pais: "França", codigo: "fr" },
    "Colombino": { pais: "Espanha", codigo: "es" },
    "Colosso da Lagoa": { estado: "Santa Catarina", uf: "SC" },
    "Colosso dos Tapajós": { estado: "Pará", uf: "PA" },
    "Correão": { estado: "Rio de Janeiro", uf: "RJ" },
    "Correão-PI": { estado: "Piauí", uf: "PI" },
    "Craven Cottage": { pais: "Inglaterra", codigo: "gb" },
    "Crystal Palace Training Ground": { pais: "Inglaterra", codigo: "gb" },
    "Cícero de Souza Marques": { estado: "São Paulo", uf: "SP" },
    "De Kuip": { pais: "Holanda", codigo: "nl" },
    "Defensores Del Chaco": { pais: "Paraguai", codigo: "py" },
    "Duarte de Paiva": { estado: "Minas Gerais", uf: "MG" },
    "Dutrinha": { estado: "Mato Grosso", uf: "MT" },
    "Eduardo Guinle": { estado: "Rio de Janeiro", uf: "RJ" },
    "El Arcangel": { pais: "Espanha", codigo: "es" },
    "El Campín": { pais: "Colômbia", codigo: "co" },
    "El Cilindro": { pais: "Argentina", codigo: "ar" },
    "El Molinón": { pais: "Espanha", codigo: "es" },
    "El Teniente": { pais: "Chile", codigo: "cl" },
    "Elland Road": { pais: "Inglaterra", codigo: "gb" },
    "Engenheiro Araripe": { estado: "Espírito Santo", uf: "ES" },
    "Engenho de Dentro": { estado: "Rio de Janeiro", uf: "RJ" },
    "Ernestão": { estado: "Santa Catarina", uf: "SC" },
    "Ernst Happel Stadion": { pais: "Áustria", codigo: "at" },
    "Esperança": { estado: "São Paulo", uf: "SP" },
    "Esperidião Geraidine": { estado: "Rio de Janeiro", uf: "RJ" },
    "Estadi de Sarriá": { pais: "Espanha", codigo: "es" },
    "Estadio Uno": { pais: "Argentina", codigo: "ar" },
    "Estrada Dona Castorina": { estado: "Rio de Janeiro", uf: "RJ" },
    "Estrada do Norte": { estado: "Rio de Janeiro", uf: "RJ" },
    "Estradinha": { estado: "Paraná", uf: "PR" },
    "Estrela d'Alva": { estado: "Rio Grande do Sul", uf: "RS" },
    "Estádio León": { pais: "México", codigo: "mx" },
    "Estádio Municipal Geraldão": { estado: "Bahia", uf: "BA" },
    "Estádio Municipal Lúcio Pipino": { estado: "Paraná", uf: "PR" },
    "Estádio Municipal de Aracaju": { estado: "Sergipe", uf: "SE" },
    "Estádio Municipal de Diamantina": { estado: "Minas Gerais", uf: "MG" },
    "Estádio Municipal de Vassouras": { estado: "Rio de Janeiro", uf: "RJ" },
    "Estádio Nacional da Costa Rica": { pais: "Costa Rica", codigo: "cr" },
    "Estádio Tecnológico": { pais: "México", codigo: "mx" },
    "Estádio da Baixada": { estado: "Paraná", uf: "PR" },
    "Estádio da Floresta": { estado: "São Paulo", uf: "SP" },
    "Estádio da Luz": { pais: "Portugal", codigo: "pt" },
    "Estádio da Mogiana": { estado: "São Paulo", uf: "SP" },
    "Estádio das Antas": { pais: "Portugal", codigo: "pt" },
    "Estádio das Oliveiras": { estado: "Rio Grande do Sul", uf: "RS" },
    "Estádio de Buenavista": { pais: "Espanha", codigo: "es" },
    "Estádio de La Condomina": { pais: "Espanha", codigo: "es" },
    "Estádio do Café": { estado: "Paraná", uf: "PR" },
    "Estádio do Mutange": { estado: "Alagoas", uf: "AL" },
    "Estádio dos Eucaliptos": { estado: "Rio Grande do Sul", uf: "RS" },
    "Estádio dos Eucaliptos (Santa Maria)": { estado: "Rio Grande do Sul", uf: "RS" },
    "Expedicionário": { estado: "Rio de Janeiro", uf: "RJ" },
    "Farião": { estado: "Minas Gerais", uf: "MG" },
    "Fazendinha": { estado: "São Paulo", uf: "SP" },
    "Fello Meza": { pais: "Costa Rica", codigo: "cr" },
    "Figueira de Melo": { estado: "Rio de Janeiro", uf: "RJ" },
    "Flor Branca": { pais: "El Salvador", codigo: "sv" },
    "Florencio Sola": { pais: "Argentina", codigo: "ar" },
    "Fonte Luminosa": { estado: "São Paulo", uf: "SP" },
    "Frankenstadion": { pais: "Alemanha", codigo: "de" },
    "Frasqueirão": { estado: "Rio Grande do Norte", uf: "RN" },
    "Fratton Park": { pais: "Inglaterra", codigo: "gb" },
    "Félix Capriles": { pais: "Bolívia", codigo: "bo" },
    "Gammliavallen": { pais: "Suécia", codigo: "se" },
    "General Affonseca": { estado: "São Paulo", uf: "SP" },
    "General Pablo Rojas": { pais: "Paraguai", codigo: "py" },
    "General Rumiñahui": { pais: "Equador", codigo: "ec" },
    "Georg Melches": { pais: "Alemanha", codigo: "de" },
    "George Capwell": { pais: "Equador", codigo: "ec" },
    "Germano Kruger": { estado: "Paraná", uf: "PR" },
    "Gerson Amaral": { estado: "Alagoas", uf: "AL" },
    "Giulite Coutinho": { estado: "Rio de Janeiro", uf: "RJ" },
    "Godofredo Cruz": { estado: "Rio de Janeiro", uf: "RJ" },
    "Governador Bley": { estado: "Espírito Santo", uf: "ES" },
    "Gran Parque Central": { pais: "Uruguai", codigo: "uy" },
    "Gran Stadium Cerveza Tropical": { pais: "Cuba", codigo: "cu" },
    "Griffin Park": { pais: "Inglaterra", codigo: "gb" },
    "Grêmio Fronteira": { estado: "Santa Catarina", uf: "SC" },
    "Guanahyro Fraga Motta": { estado: "Minas Gerais", uf: "MG" },
    "Gumercindo Rodrigues Neves": { estado: "Minas Gerais", uf: "MG" },
    "Hanói Stadium": { pais: "Vietnã", codigo: "vn" },
    "Hardturm": { pais: "Suíça", codigo: "ch" },
    "Heitor Bravo": { estado: "Rio de Janeiro", uf: "RJ" },
    "Heriberto Hulse": { estado: "Santa Catarina", uf: "SC" },
    "Hermenegildo Barcelos": { estado: "Rio de Janeiro", uf: "RJ" },
    "Hernando Siles": { pais: "Bolívia", codigo: "bo" },
    "Home Park": { pais: "Inglaterra", codigo: "gb" },
    "Houphouet Boigny": { pais: "Costa do Marfim", codigo: "ci" },
    "Independence Park": { pais: "Jamaica", codigo: "jm" },
    "Ipatingão": { estado: "Minas Gerais", uf: "MG" },
    "Israel Pinheiro (Brasília)": { estado: "Distrito Federal", uf: "DF" },
    "Israel Pinheiro (Itabira)": { estado: "Minas Gerais", uf: "MG" },
    "Itabunão": { estado: "Bahia", uf: "BA" },
    "Jair Bittencourt": { estado: "Rio de Janeiro", uf: "RJ" },
    "Jalisco": { pais: "México", codigo: "mx" },
    "Jayme Cintra": { estado: "São Paulo", uf: "SP" },
    "Joaquim Portugal": { estado: "Minas Gerais", uf: "MG" },
    "Joaquim de Paula Xavier": { estado: "Paraná", uf: "PR" },
    "Joia da Princesa": { estado: "Bahia", uf: "BA" },
    "Jonas Duarte": { estado: "Goiás", uf: "GO" },
    "José Fragelli": { estado: "Mato Grosso", uf: "MT" },
    "José Liberatti": { estado: "São Paulo", uf: "SP" },
    "José Paiz Soares": { estado: "Minas Gerais", uf: "MG" },
    "Joviniano Dourado Lopes": { estado: "Bahia", uf: "BA" },
    "Juca Ribeiro": { estado: "Minas Gerais", uf: "MG" },
    "Juscelino Kubitschek-GO": { estado: "Goiás", uf: "GO" },
    "Juscelino Kubitschek-MG": { estado: "Minas Gerais", uf: "MG" },
    "Justiniano de Melo e Silva": { estado: "Espírito Santo", uf: "ES" },
    "Juvenal Lamartine": { estado: "Rio Grande do Norte", uf: "RN" },
    "Kobe Universiade Memorial": { pais: "Japão", codigo: "jp" },
    "La Beaujoire": { pais: "França", codigo: "fr" },
    "La Doble Visera": { pais: "Argentina", codigo: "ar" },
    "La Huerta": { pais: "Paraguai", codigo: "py" },
    "La Rosaleda": { pais: "Espanha", codigo: "es" },
    "Lacerdão": { estado: "Pernambuco", uf: "PE" },
    "Les Corts": { pais: "Espanha", codigo: "es" },
    "Limeirão": { estado: "São Paulo", uf: "SP" },
    "Lincoln Financial Field": { pais: "Estados Unidos", codigo: "us" },
    "Lindolfo Monteiro": { estado: "Piauí", uf: "PI" },
    "London Road": { pais: "Inglaterra", codigo: "gb" },
    "Los Angeles Memorial Coliseum": { pais: "Estados Unidos", codigo: "us" },
    "Los Larios": { estado: "Rio de Janeiro", uf: "RJ" },
    "Lourdes": { estado: "Minas Gerais", uf: "MG" },
    "Louzadão": { estado: "Rio de Janeiro", uf: "RJ" },
    "Ludwigspark Stadion": { pais: "Alemanha", codigo: "de" },
    "Luis Afonso Giagni": { pais: "Paraguai", codigo: "py" },
    "Luis Pirata Fuente": { pais: "México", codigo: "mx" },
    "Lumen Field": { pais: "Estados Unidos", codigo: "us" },
    "Luís Sitjar": { pais: "Espanha", codigo: "es" },
    "Machadão": { estado: "Rio Grande do Norte", uf: "RN" },
    "Maião": { estado: "São Paulo", uf: "SP" },
    "Malmo Stadion": { pais: "Suécia", codigo: "se" },
    "Mamudão": { estado: "Minas Gerais", uf: "MG" },
    "Manduzão": { estado: "Minas Gerais", uf: "MG" },
    "Mangueirão": { estado: "Pará", uf: "PA" },
    "Mansiche": { pais: "Peru", codigo: "pe" },
    "Marechal Hermes": { estado: "Rio de Janeiro", uf: "RJ" },
    "Martins Pereira": { estado: "São Paulo", uf: "SP" },
    "Mauritsstadion": { pais: "Holanda", codigo: "nl" },
    "Melão": { estado: "Minas Gerais", uf: "MG" },
    "Mestalla": { pais: "Espanha", codigo: "es" },
    "Metropolitano": { pais: "Espanha", codigo: "es" },
    "Metropolitano Roberto Meléndez": { pais: "Colômbia", codigo: "co" },
    "Misael Delgado": { pais: "Venezuela", codigo: "ve" },
    "Mithatpasa": { pais: "Turquia", codigo: "tr" },
    "Moacyrzão": { estado: "Rio de Janeiro", uf: "RJ" },
    "Mohammed V": { pais: "Marrocos", codigo: "ma" },
    "Moisés Lucarelli": { estado: "São Paulo", uf: "SP" },
    "Monumental Banco Pichincha": { pais: "Equador", codigo: "ec" },
    "Monumental David Arellano": { pais: "Chile", codigo: "cl" },
    "Monumental U": { pais: "Peru", codigo: "pe" },
    "Monumental do Sesi": { estado: "Santa Catarina", uf: "SC" },
    "Moraes e Silva": { estado: "Rio de Janeiro", uf: "RJ" },
    "Morenão": { estado: "Mato Grosso do Sul", uf: "MS" },
    "Munsu Stadium": { pais: "Coreia do Sul", codigo: "kr" },
    "Mário Alves Mendonça": { estado: "São Paulo", uf: "SP" },
    "Nacional (Lima)": { pais: "Peru", codigo: "pe" },
    "Nacional (Tóquio)": { pais: "Japão", codigo: "jp" },
    "Nacional Brígido Iriarte": { pais: "Venezuela", codigo: "ve" },
    "Nacional de Chile": { pais: "Chile", codigo: "cl" },
    "Nacional de Dakar": { pais: "Senegal", codigo: "sn" },
    "Nacional de Oran": { pais: "Argélia", codigo: "dz" },
    "Nagai Stadium": { pais: "Japão", codigo: "jp" },
    "Nassri Mattar": { estado: "Minas Gerais", uf: "MG" },
    "Nep Stadium": { pais: "Hungria", codigo: "hu" },
    "Nhozinho Santos": { estado: "Maranhão", uf: "MA" },
    "Nildo Pereira de Menezes": { estado: "Pernambuco", uf: "PE" },
    "Ninian Park": { pais: "Inglaterra", codigo: "gb" },
    "Norberto Tito Tomaghello": { pais: "Argentina", codigo: "ar" },
    "Nuevo Gasometro": { pais: "Argentina", codigo: "ar" },
    "Népstadion": { pais: "Hungria", codigo: "hu" },
    "OBA": { estado: "Goiás", uf: "GO" },
    "Odair Gama": { estado: "Rio de Janeiro", uf: "RJ" },
    "Olímpico (Goiânia)": { estado: "Goiás", uf: "GO" },
    "Olímpico Atahualpa": { pais: "Equador", codigo: "ec" },
    "Olímpico Universitario": { pais: "México", codigo: "mx" },
    "Olímpico de Amsterdam": { pais: "Holanda", codigo: "nl" },
    "Olímpico de Amsterdã": { pais: "Holanda", codigo: "nl" },
    "Olímpico de Caracas": { pais: "Venezuela", codigo: "ve" },
    "Olímpico de Roma": { pais: "Itália", codigo: "it" },
    "Olímpico-RS": { estado: "Rio Grande do Sul", uf: "RS" },
    "Omiya": { pais: "Japão", codigo: "jp" },
    "Orlando Mattos": { estado: "Paraná", uf: "PR" },
    "Orlando Scarpelli": { estado: "Santa Catarina", uf: "SC" },
    "Otacílio Negrão de Lima": { estado: "Minas Gerais", uf: "MG" },
    "Palestra Itália": { estado: "São Paulo", uf: "SP" },
    "Palma Travassos": { estado: "São Paulo", uf: "SP" },
    "Parc Astrid": { pais: "Bélgica", codigo: "be" },
    "Parc Des Princes": { pais: "França", codigo: "fr" },
    "Parque Asturias": { pais: "México", codigo: "mx" },
    "Parque da Graciosa": { estado: "Paraná", uf: "PR" },
    "Pascual Guerrero": { pais: "Colômbia", codigo: "co" },
    "Passo das Emas": { estado: "Mato Grosso", uf: "MT" },
    "Paulo Fernandes": { estado: "Rio de Janeiro", uf: "RJ" },
    "Pelezão": { estado: "Distrito Federal", uf: "DF" },
    "Petrônio Portela": { estado: "Piauí", uf: "PI" },
    "Pinheirão": { estado: "Paraná", uf: "PR" },
    "Pituaçu": { estado: "Bahia", uf: "BA" },
    "Playa Ancha": { pais: "Chile", codigo: "cl" },
    "Plínio Lemos": { estado: "Paraíba", uf: "PB" },
    "Prado Mineiro": { estado: "Minas Gerais", uf: "MG" },
    "Praia Vermelha": { estado: "Rio de Janeiro", uf: "RJ" },
    "Presbítero Bartolomé Grella": { pais: "Argentina", codigo: "ar" },
    "Presidente Vargas": { estado: "Ceará", uf: "CE" },
    "Presidente Vargas (Campina Grande)": { estado: "Paraíba", uf: "PB" },
    "Prince Abdullah al-Faisal": { pais: "Arábia Saudita", codigo: "sa" },
    "Prudentão": { estado: "São Paulo", uf: "SP" },
    "Puerto Sajonia": { pais: "Paraguai", codigo: "py" },
    "Raiz da Serra": { estado: "Rio de Janeiro", uf: "RJ" },
    "Ramón de Carranza": { pais: "Espanha", codigo: "es" },
    "Rasunda": { pais: "Suécia", codigo: "se" },
    "Raul Sertã": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rei Pelé": { estado: "Alagoas", uf: "AL" },
    "Ressacada": { estado: "Santa Catarina", uf: "SC" },
    "Riazor": { pais: "Espanha", codigo: "es" },
    "Ricardo Saprissa": { pais: "Costa Rica", codigo: "cr" },
    "Rodríguez López": { pais: "Espanha", codigo: "es" },
    "Romeirão": { estado: "Ceará", uf: "CE" },
    "Ronaldão": { estado: "Minas Gerais", uf: "MG" },
    "Rose Bowl": { pais: "Estados Unidos", codigo: "us" },
    "Rua Bariri": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Constituição": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Cândido Silva": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Desembargador Isidro": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Domingos Lopes": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Doutor March": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Dr. Paulo Cézar": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Ferrer": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua General Silva Teles": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Javari": { estado: "São Paulo", uf: "SP" },
    "Rua João Pinheiro": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Magalhães Castro": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Paysandu": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua São Clemente": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua São Lourenço": { estado: "Rio de Janeiro", uf: "RJ" },
    "Rua Tibiriçá": { estado: "São Paulo", uf: "SP" },
    "Rubens Gomes": { estado: "Espírito Santo", uf: "ES" },
    "Salles Oliveira": { estado: "Minas Gerais", uf: "MG" },
    "San Carlos de Apoquindo": { pais: "Chile", codigo: "cl" },
    "San Nanes": { pais: "Espanha", codigo: "es" },
    "San Paolo": { pais: "Itália", codigo: "it" },
    "San Siro": { pais: "Itália", codigo: "it" },
    "Santa Cruz": { estado: "São Paulo", uf: "SP" },
    "Santa Laura": { pais: "Chile", codigo: "cl" },
    "Santa Tereza": { estado: "Minas Gerais", uf: "MG" },
    "Sausalito": { pais: "Chile", codigo: "cl" },
    "Sebastião César da Silva": { estado: "Minas Gerais", uf: "MG" },
    "Selhurst Park": { pais: "Inglaterra", codigo: "gb" },
    "Serejão": { estado: "Distrito Federal", uf: "DF" },
    "Serra Dourada": { estado: "Goiás", uf: "GO" },
    "Serrinha": { estado: "Goiás", uf: "GO" },
    "Stade Auguste Delaune": { pais: "França", codigo: "fr" },
    "Stade Félix Bollaert": { pais: "França", codigo: "fr" },
    "Stade Jules Deschaseaux": { pais: "França", codigo: "fr" },
    "Stade de Venoix": { pais: "França", codigo: "fr" },
    "Stade de l'Aube": { pais: "França", codigo: "fr" },
    "Stadio Comunale": { pais: "Itália", codigo: "it" },
    "Stadio Olimpico Grande Torino": { pais: "Itália", codigo: "it" },
    "Stadion Slavia": { pais: "República Tcheca", codigo: "cz" },
    "Stadium 974": { pais: "Catar", codigo: "qa" },
    "Stadium Nord": { pais: "França", codigo: "fr" },
    "Stará střelnice": { pais: "República Tcheca", codigo: "cz" },
    "Strahov": { pais: "República Tcheca", codigo: "cz" },
    "Sumaré": { estado: "Espírito Santo", uf: "ES" },
    "Tehelné Pole": { pais: "Eslováquia", codigo: "sk" },
    "Teixeira de Castro": { estado: "Rio de Janeiro", uf: "RJ" },
    "Tiezão": { estado: "Rio de Janeiro", uf: "RJ" },
    "Tupy Cantanhede": { estado: "Pará", uf: "PA" },
    "Turf Moor": { pais: "Inglaterra", codigo: "gb" },
    "Tóquio Dome Stadium": { pais: "Japão", codigo: "jp" },
    "Uberabão": { estado: "Minas Gerais", uf: "MG" },
    "Ullevi": { pais: "Suécia", codigo: "se" },
    "Ulrico Mursa": { estado: "São Paulo", uf: "SP" },
    "Universitário de Caracas": { pais: "Venezuela", codigo: "ve" },
    "VGD": { estado: "Paraná", uf: "PR" },
    "Vail Chaves": { estado: "São Paulo", uf: "SP" },
    "Verdão": { estado: "Mato Grosso", uf: "MT" },
    "Viejo Gasometro": { pais: "Argentina", codigo: "ar" },
    "Vila Capanema": { estado: "Paraná", uf: "PR" },
    "Vila Olímpica Parahyba": { estado: "Paraíba", uf: "PB" },
    "Vivaldão": { estado: "Amazonas", uf: "AM" },
    "Voluntários da Pátria": { estado: "Rio de Janeiro", uf: "RJ" },
    "Víctor Agustín Ugarte": { pais: "Bolívia", codigo: "bo" },
    "Waldermar de Brito": { estado: "Santa Catarina", uf: "SC" },
    "Waldomirão": { estado: "Bahia", uf: "BA" },
    "Wankdorf Stadium": { pais: "Suíça", codigo: "ch" },
    "Wildparkstadion": { pais: "Alemanha", codigo: "de" },
    "Zenor Pedrosa Rocha": { estado: "Espírito Santo", uf: "ES" },
    "Zequinha Roriz": { estado: "Goiás", uf: "GO" },
    "Ítalo del Cima": { estado: "Rio de Janeiro", uf: "RJ" },
};

export default estadiosLocais;
