const paises = {
    "Atlético Nacional":       { pais: "Colômbia",  codigo: "co" },
    "Audax Italiano":          { pais: "Chile",      codigo: "cl" },
    "Aurora":                  { pais: "Bolívia",    codigo: "bo" },
    "Barcelona de Guayaquil":  { pais: "Equador",    codigo: "ec" },
    "Carabobo":                { pais: "Venezuela",  codigo: "ve" },
    "Caracas":                 { pais: "Venezuela",  codigo: "ve" },
    "Colo-Colo":               { pais: "Chile",      codigo: "cl" },
    "César Vallejo":           { pais: "Peru",       codigo: "pe" },
    "Defensa y Justicia":      { pais: "Argentina",  codigo: "ar" },
    "Deportivo Quito":         { pais: "Equador",    codigo: "ec" },
    "Estudiantes":             { pais: "Argentina",  codigo: "ar" },
    "Guarani-PAR":             { pais: "Paraguai",   codigo: "py" },
    "Independiente Del Valle": { pais: "Equador",    codigo: "ec" },
    "Independiente Petrolero": { pais: "Bolívia",    codigo: "bo" },
    "Junior Barranquilla":     { pais: "Colômbia",   codigo: "co" },
    "LDU":                     { pais: "Equador",    codigo: "ec" },
    "Magallanes":              { pais: "Chile",      codigo: "cl" },
    "Nacional Potosí":         { pais: "Bolívia",    codigo: "bo" },
    "Nacional-PAR":            { pais: "Paraguai",   codigo: "py" },
    "Nacional-URU":            { pais: "Uruguai",    codigo: "uy" },
    "Olimpia":                 { pais: "Paraguai",   codigo: "py" },
    "Patronato":               { pais: "Argentina",  codigo: "ar" },
    "Peñarol":                 { pais: "Uruguai",    codigo: "uy" },
    "Racing":                  { pais: "Argentina",  codigo: "ar" },
    "Sol de America":          { pais: "Paraguai",   codigo: "py" },
    "Universidad de Chile":    { pais: "Chile",      codigo: "cl" },
    "Universitario":           { pais: "Peru",       codigo: "pe" },
};

export default paises;
