let jogos = [
    { "mandante": "Portuguesa-RJ", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Carioca 2026", "data": "2026-01-15", "estadio": "Luso Brasileiro", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "Fortaleza", "golsMandante": 4, "golsVisitante": 2, "campeonato": "Brasileirão 2025", "data": "2025-12-07", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Sport", "golsMandante": 3, "golsVisitante": 2, "campeonato": "Brasileirão 2025", "data": "2025-11-18", "estadio": "Nilton Santos", "horario": "20:30" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Brasileirão 2025", "data": "2025-11-05", "estadio": "Nilton Santos", "horario": "19:30" },
    { "mandante": "Botafogo", "visitante": "Santos", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Brasileirão 2025", "data": "2025-10-26", "estadio": "Nilton Santos", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Flamengo", "golsMandante": 0, "golsVisitante": 3, "campeonato": "Brasileirão 2025", "data": "2025-10-15", "estadio": "Nilton Santos", "horario": "19:30" },
    { "mandante": "Botafogo", "visitante": "Bahia", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2025", "data": "2025-10-01", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2025", "data": "2025-09-28", "estadio": "Maracanã", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2025", "data": "2025-09-20", "estadio": "Nilton Santos", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Mirassol", "golsMandante": 3, "golsVisitante": 3, "campeonato": "Brasileirão 2025", "data": "2025-09-17", "estadio": "Nilton Santos", "horario": "19:30" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Copa do Brasil 2025", "data": "2025-09-11", "estadio": "Nilton Santos", "horario": "21:30", "penaltis": "3 x 5" },
    { "mandante": "Botafogo", "visitante": "Red Bull Bragantino", "golsMandante": 4, "golsVisitante": 1, "campeonato": "Brasileirão 2025", "data": "2025-08-30", "estadio": "Nilton Santos", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Palmeiras", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2025", "data": "2025-08-17", "estadio": "Nilton Santos", "horario": "20:30" },
    { "mandante": "Botafogo", "visitante": "LDU", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Libertadores 2025", "data": "2025-08-14", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "Cruzeiro", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Brasileirão 2025", "data": "2025-08-03", "estadio": "Nilton Santos", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Red Bull Bragantino", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Copa do Brasil 2025", "data": "2025-07-29", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "Corinthians", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2025", "data": "2025-07-26", "estadio": "Nilton Santos", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Vitória", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2025", "data": "2025-07-16", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Ceará", "golsMandante": 3, "golsVisitante": 2, "campeonato": "Brasileirão 2025", "data": "2025-06-04", "estadio": "Nilton Santos", "horario": "20:00" },
    { "mandante": "Botafogo", "visitante": "Universidad de Chile", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Libertadores 2025", "data": "2025-05-27", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2025", "data": "2025-05-18", "estadio": "Maracanã", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Estudiantes", "golsMandante": 3, "golsVisitante": 2, "campeonato": "Libertadores 2025", "data": "2025-05-14", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Internacional", "golsMandante": 4, "golsVisitante": 0, "campeonato": "Brasileirão 2025", "data": "2025-05-11", "estadio": "Nilton Santos", "horario": "20:00" },
    { "mandante": "Botafogo", "visitante": "Capital", "golsMandante": 4, "golsVisitante": 0, "campeonato": "Copa do Brasil 2025", "data": "2025-04-30", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2025", "data": "2025-04-26", "estadio": "Nilton Santos", "horario": "21:00" },
    { "mandante": "Botafogo", "visitante": "São Paulo", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Brasileirão 2025", "data": "2025-04-16", "estadio": "Nilton Santos", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Carabobo", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Libertadores 2025", "data": "2025-04-08", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "Juventude", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2025", "data": "2025-04-05", "estadio": "Nilton Santos", "horario": "21:00" },
    { "mandante": "Palmeiras", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2025", "data": "2025-03-30", "estadio": "Allianz Parque", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Novorizontino", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Amistoso", "data": "2025-03-22", "estadio": "Nilton Santos", "horario": "16:15" },
    { "mandante": "Botafogo", "visitante": "Racing", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Recopa 2025", "data": "2025-02-27", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2025", "data": "2025-02-23", "estadio": "São Januário", "horario": "18:30" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2025", "data": "2025-02-12", "estadio": "Maracanã", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Madureira", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Carioca 2025", "data": "2025-02-09", "estadio": "Kleber Andrade", "horario": "16:00" },
    { "mandante": "Nova Iguaçu", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Carioca 2025", "data": "2025-02-06", "estadio": "Moça Bonita", "horario": "21:45" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2025", "data": "2025-01-29", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Bangu", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2025", "data": "2025-01-26", "estadio": "Nilton Santos", "horario": "18:00" },
    { "mandante": "Botafogo", "visitante": "Volta Redonda", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Carioca 2025", "data": "2025-01-22", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Sampaio Corrêa-RJ", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2025", "data": "2025-01-18", "estadio": "Lourivaldão", "horario": "16:30" },
    { "mandante": "Botafogo", "visitante": "Portuguesa-RJ", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2025", "data": "2025-01-14", "estadio": "Nilton Santos", "horario": "19:30" },
    { "mandante": "Botafogo", "visitante": "Maricá", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Carioca 2025", "data": "2025-01-11", "estadio": "Nilton Santos", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "São Paulo", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2024", "data": "2024-12-08", "estadio": "Nilton Santos", "horario": "16:00" },
    { "mandante": "Atlético-MG", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 3, "campeonato": "Libertadores 2024", "data": "2024-11-30", "estadio": "Monumental de Núñez", "horario": "17:00" },
    { "mandante": "Palmeiras", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 3, "campeonato": "Brasileirão 2024", "data": "2024-11-26", "estadio": "Allianz Parque", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Vitória", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2024", "data": "2024-11-23", "estadio": "Nilton Santos", "horario": "19:30" },
    { "mandante": "Botafogo", "visitante": "Cuiabá", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2024", "data": "2024-11-09", "estadio": "Nilton Santos", "horario": "16:30" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Brasileirão 2024", "data": "2024-11-05", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Peñarol", "visitante": "Botafogo", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Libertadores 2024", "data": "2024-10-30", "estadio": "Centenario-URU", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Peñarol", "golsMandante": 5, "golsVisitante": 0, "campeonato": "Libertadores 2024", "data": "2024-10-23", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Criciúma", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2024", "data": "2024-10-18", "estadio": "Maracanã", "horario": "20:00" },
    { "mandante": "São Paulo", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Libertadores 2024", "data": "2024-09-25", "estadio": "Morumbi", "horario": "21:30", "penaltis": "4 x 5" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2024", "data": "2024-09-21", "estadio": "Maracanã", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "São Paulo", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Libertadores 2024", "data": "2024-09-18", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Corinthians", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2024", "data": "2024-09-14", "estadio": "Nilton Santos", "horario": "21:00" },
    { "mandante": "Palmeiras", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Libertadores 2024", "data": "2024-08-21", "estadio": "Allianz Parque", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Flamengo", "golsMandante": 4, "golsVisitante": 1, "campeonato": "Brasileirão 2024", "data": "2024-08-18", "estadio": "Nilton Santos", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Palmeiras", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Libertadores 2024", "data": "2024-08-14", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Bahia", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Copa do Brasil 2024", "data": "2024-07-30", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Cruzeiro", "golsMandante": 0, "golsVisitante": 3, "campeonato": "Brasileirão 2024", "data": "2024-07-27", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Internacional", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2024", "data": "2024-07-20", "estadio": "Nilton Santos", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Palmeiras", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2024", "data": "2024-07-17", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Brasileirão 2024", "data": "2024-07-07", "estadio": "Nilton Santos", "horario": "20:30" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2024", "data": "2024-06-29", "estadio": "São Januário", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Red Bull Bragantino", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2024", "data": "2024-06-26", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "Athletico-PR", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2024", "data": "2024-06-19", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2024", "data": "2024-06-11", "estadio": "Nilton Santos", "horario": "20:00" },
    { "mandante": "Vitória", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Copa do Brasil 2024", "data": "2024-05-22", "estadio": "Barradão", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "LDU", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Libertadores 2024", "data": "2024-05-08", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Botafogo", "visitante": "Bahia", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Brasileirão 2024", "data": "2024-05-05", "estadio": "Nilton Santos", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Vitória", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Copa do Brasil 2024", "data": "2024-05-02", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Brasileirão 2024", "data": "2024-04-28", "estadio": "Maracanã", "horario": "11:00" },
    { "mandante": "Botafogo", "visitante": "Universitario", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Libertadores 2024", "data": "2024-04-24", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "Juventude", "golsMandante": 5, "golsVisitante": 1, "campeonato": "Brasileirão 2024", "data": "2024-04-21", "estadio": "Nilton Santos", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Atlético-GO", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2024", "data": "2024-04-18", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Cruzeiro", "visitante": "Botafogo", "golsMandante": 3, "golsVisitante": 2, "campeonato": "Brasileirão 2024", "data": "2024-04-14", "estadio": "Mineirão", "horario": "17:00" },
    { "mandante": "Botafogo", "visitante": "Junior Barranquilla", "golsMandante": 1, "golsVisitante": 3, "campeonato": "Libertadores 2024", "data": "2024-04-03", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "Boavista", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2024", "data": "2024-03-31", "estadio": "Nilton Santos", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Sampaio Corrêa-RJ", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2024", "data": "2024-03-17", "estadio": "Nilton Santos", "horario": "18:30" },
    { "mandante": "Sampaio Corrêa-RJ", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Carioca 2024", "data": "2024-03-10", "estadio": "Elcyr Resende", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Red Bull Bragantino", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Libertadores 2024", "data": "2024-03-06", "estadio": "Nilton Santos", "horario": "21:30" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 4, "campeonato": "Carioca 2024", "data": "2024-03-03", "estadio": "Maracanã", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Aurora", "golsMandante": 6, "golsVisitante": 0, "campeonato": "Libertadores 2024", "data": "2024-02-28", "estadio": "Nilton Santos" },
    { "mandante": "Audax Rio", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Carioca 2024", "data": "2024-02-24", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 2, "golsVisitante": 4, "campeonato": "Carioca 2024", "data": "2024-02-18", "estadio": "Nilton Santos" },
    { "mandante": "Volta Redonda", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 3, "campeonato": "Carioca 2024", "data": "2024-02-14", "estadio": "Raulino de Oliveira" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2024", "data": "2024-02-07", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Portuguesa-RJ", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Carioca 2024", "data": "2024-01-30", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Sampaio Corrêa-RJ", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2024", "data": "2024-01-27", "estadio": "Nilton Santos" },
    { "mandante": "Boavista", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2024", "data": "2024-01-24", "estadio": "Elcyr Resende" },
    { "mandante": "Botafogo", "visitante": "Bangu", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2024", "data": "2024-01-20", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Madureira", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2024", "data": "2024-01-17", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Cruzeiro", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-12-03", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Santos", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2023", "data": "2023-11-26", "estadio": "Nilton Santos" },
    { "mandante": "Red Bull Bragantino", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Brasileirão 2023", "data": "2023-11-12", "estadio": "Nabi Abi Chedid" },
    { "mandante": "Botafogo", "visitante": "Grêmio", "golsMandante": 3, "golsVisitante": 4, "campeonato": "Brasileirão 2023", "data": "2023-11-09", "estadio": "São Januário" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-11-06", "estadio": "São Januário" },
    { "mandante": "Botafogo", "visitante": "Palmeiras", "golsMandante": 3, "golsVisitante": 4, "campeonato": "Brasileirão 2023", "data": "2023-11-01", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Cuiabá", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2023", "data": "2023-10-29", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Athletico-PR", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2023", "data": "2023-10-21", "estadio": "Nilton Santos", "horario": "21:00" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Brasileirão 2023", "data": "2023-10-08", "estadio": "Maracanã", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Goiás", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2023", "data": "2023-10-02", "estadio": "Nilton Santos", "horario": "20:00" },
    { "mandante": "Corinthians", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-09-22", "estadio": "Neo Química Arena", "horario": "20:00" },
    { "mandante": "Atlético-MG", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-09-16", "estadio": "Arena MRV", "horario": "21:00" },
    { "mandante": "Botafogo", "visitante": "Flamengo", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Brasileirão 2023", "data": "2023-09-02", "estadio": "Nilton Santos", "horario": "21:00" },
    { "mandante": "Botafogo", "visitante": "Bahia", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-08-27", "estadio": "Nilton Santos", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Defensa y Justicia", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Copa Sul-Americana 2023", "data": "2023-08-23", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "São Paulo", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-08-19", "estadio": "Morumbi", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Internacional", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Brasileirão 2023", "data": "2023-08-12", "estadio": "Nilton Santos", "horario": "21:00" },
    { "mandante": "Cruzeiro", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-08-06", "estadio": "Mineirão", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Guarani-PAR", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Copa Sul-Americana 2023", "data": "2023-08-02", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "Coritiba", "golsMandante": 4, "golsVisitante": 1, "campeonato": "Brasileirão 2023", "data": "2023-07-30", "estadio": "Nilton Santos", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Patronato", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Copa Sul-Americana 2023", "data": "2023-07-19", "estadio": "Nilton Santos", "horario": "19:00" },
    { "mandante": "Botafogo", "visitante": "Red Bull Bragantino", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-07-15", "estadio": "Nilton Santos", "horario": "21:00" },
    { "mandante": "Grêmio", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Brasileirão 2023", "data": "2023-07-09", "estadio": "Arena do Grêmio", "horario": "18:30" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-07-02", "estadio": "Nilton Santos", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Magallanes", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Copa Sul-Americana 2023", "data": "2023-06-29", "estadio": "Nilton Santos", "horario": "21:00" },
    { "mandante": "Palmeiras", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2023", "data": "2023-06-25", "estadio": "Allianz Parque", "horario": "16:00" },
    { "mandante": "Botafogo", "visitante": "Fortaleza", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-06-10", "estadio": "Nilton Santos" },
    { "mandante": "Athletico-PR", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-06-03", "estadio": "Arena da Baixada" },
    { "mandante": "Botafogo", "visitante": "Athletico-PR", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Copa do Brasil 2023", "data": "2023-05-31", "estadio": "Nilton Santos", "penaltis": "2 x 4" },
    { "mandante": "Botafogo", "visitante": "América-MG", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-05-28", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-05-20", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Corinthians", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-05-11", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2023", "data": "2023-05-07", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "LDU", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Copa Sul-Americana 2023", "data": "2023-05-04", "estadio": "Nilton Santos" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 3, "campeonato": "Brasileirão 2023", "data": "2023-04-30", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Ypiranga", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Copa do Brasil 2023", "data": "2023-04-27", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "César Vallejo", "golsMandante": 4, "golsVisitante": 0, "campeonato": "Copa Sul-Americana 2023", "data": "2023-04-20", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "São Paulo", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2023", "data": "2023-04-15", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Audax Rio", "golsMandante": 5, "golsVisitante": 2, "campeonato": "Carioca 2023", "data": "2023-04-09", "estadio": "Raulino de Oliveira" },
    { "mandante": "Audax Rio", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Carioca 2023", "data": "2023-04-02", "estadio": "Raulino de Oliveira" },
    { "mandante": "Botafogo", "visitante": "Portuguesa-RJ", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Carioca 2023", "data": "2023-03-27", "estadio": "Raulino de Oliveira" },
    { "mandante": "Portuguesa-RJ", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Carioca 2023", "data": "2023-03-18", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Portuguesa-RJ", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Carioca 2023", "data": "2023-03-08", "estadio": "Raulino de Oliveira" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2023", "data": "2023-02-16", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Bangu", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2023", "data": "2023-02-11", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Nova Iguaçu", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Carioca 2023", "data": "2023-02-01", "estadio": "Luso Brasileiro" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Carioca 2023", "data": "2023-01-29", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Madureira", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2023", "data": "2023-01-26", "estadio": "Luso Brasileiro" },
    { "mandante": "Volta Redonda", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Carioca 2023", "data": "2023-01-19", "estadio": "Raulino de Oliveira" },
    { "mandante": "Botafogo", "visitante": "Audax Rio", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Carioca 2023", "data": "2023-01-15", "estadio": "Nilton Santos" },
    { "mandante": "Athletico-PR", "visitante": "Botafogo", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Brasileirão 2022", "data": "2022-11-13", "estadio": "Arena da Baixada" },
    { "mandante": "Botafogo", "visitante": "Santos", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Brasileirão 2022", "data": "2022-11-10", "estadio": "Nilton Santos" },
    { "mandante": "Atlético-MG", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Brasileirão 2022", "data": "2022-11-07", "estadio": "Mineirão" },
    { "mandante": "Botafogo", "visitante": "Cuiabá", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Brasileirão 2022", "data": "2022-11-01", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Red Bull Bragantino", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2022", "data": "2022-10-26", "estadio": "Nilton Santos" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Brasileirão 2022", "data": "2022-10-23", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Internacional", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2022", "data": "2022-10-16", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Palmeiras", "golsMandante": 1, "golsVisitante": 3, "campeonato": "Brasileirão 2022", "data": "2022-10-03", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Coritiba", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2022", "data": "2022-09-17", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "América-MG", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2022", "data": "2022-09-11", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Flamengo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2022", "data": "2022-08-28", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Atlético-GO", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2022", "data": "2022-08-13", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Ceará", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2022", "data": "2022-08-06", "estadio": "Nilton Santos" },
    { "mandante": "Corinthians", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2022", "data": "2022-07-30", "estadio": "Neo Química Arena" },
    { "mandante": "Botafogo", "visitante": "Athletico-PR", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2022", "data": "2022-07-23", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2022", "data": "2022-07-17", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "América-MG", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Copa do Brasil 2022", "data": "2022-07-14", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2022", "data": "2022-06-26", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "São Paulo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2022", "data": "2022-06-16", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Avaí", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2022", "data": "2022-06-13", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Goiás", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Brasileirão 2022", "data": "2022-06-06", "estadio": "Nilton Santos" },
    { "mandante": "Coritiba", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2022", "data": "2022-05-29", "estadio": "Couto Pereira" },
    { "mandante": "Botafogo", "visitante": "Fortaleza", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Brasileirão 2022", "data": "2022-05-15", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Ceilândia", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Copa do Brasil 2022", "data": "2022-05-12", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Juventude", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2022", "data": "2022-05-01", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Corinthians", "golsMandante": 1, "golsVisitante": 3, "campeonato": "Brasileirão 2022", "data": "2022-04-10", "estadio": "Nilton Santos" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Carioca 2022", "data": "2022-03-27", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Carioca 2022", "data": "2022-03-21", "estadio": "Nilton Santos" },
    { "mandante": "Audax Rio", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Carioca 2022", "data": "2022-03-13", "estadio": "Jair Toscano" },
    { "mandante": "Botafogo", "visitante": "Volta Redonda", "golsMandante": 5, "golsVisitante": 0, "campeonato": "Carioca 2022", "data": "2022-03-07", "estadio": "Nilton Santos" },
    { "mandante": "Portuguesa-RJ", "visitante": "Botafogo", "golsMandante": 5, "golsVisitante": 3, "campeonato": "Carioca 2022", "data": "2022-02-27", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Flamengo", "golsMandante": 1, "golsVisitante": 3, "campeonato": "Carioca 2022", "data": "2022-02-23", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Resende", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2022", "data": "2022-02-17", "estadio": "Nilton Santos" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2022", "data": "2022-02-10", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Nova Iguaçu", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2022", "data": "2022-02-07", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Madureira", "golsMandante": 4, "golsVisitante": 2, "campeonato": "Carioca 2022", "data": "2022-02-03", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Bangu", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2022", "data": "2022-01-30", "estadio": "Nilton Santos" },
    { "mandante": "Boavista", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Carioca 2022", "data": "2022-01-25", "estadio": "Nilton Santos" },
    { "mandante": "Taubaté", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Copinha 2022", "data": "2022-01-09", "estadio": "Joaquim de Morais Filho" },
    { "mandante": "Botafogo", "visitante": "Guarani", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Série B 2021", "data": "2021-11-28", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Operário-PR", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Série B 2021", "data": "2021-11-15", "estadio": "Nilton Santos" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 4, "campeonato": "Série B 2021", "data": "2021-11-07", "estadio": "São Januário" },
    { "mandante": "Botafogo", "visitante": "Confiança", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Série B 2021", "data": "2021-11-03", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Brusque", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Série B 2021", "data": "2021-10-20", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "CRB", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Série B 2021", "data": "2021-10-08", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Avaí", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Série B 2021", "data": "2021-10-02", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Sampaio Corrêa", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Série B 2021", "data": "2021-09-26", "estadio": "Nilton Santos" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Carioca 2020", "data": "2020-03-07", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Boavista", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2020", "data": "2020-03-01", "estadio": "Nilton Santos" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Carioca 2020", "data": "2020-02-09", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2020", "data": "2020-02-02", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Resende", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2020", "data": "2020-01-30", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Macaé", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Carioca 2020", "data": "2020-01-26", "estadio": "Nilton Santos" },
    { "mandante": "Madureira", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2020", "data": "2020-01-21", "estadio": "Conselheiro Galvão" },
    { "mandante": "Volta Redonda", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2020", "data": "2020-01-18", "estadio": "Raulino de Oliveira" },
    { "mandante": "Botafogo", "visitante": "Ceará", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2019", "data": "2019-12-08", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Internacional", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2019", "data": "2019-11-30", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Corinthians", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2019", "data": "2019-11-24", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Avaí", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2019", "data": "2019-11-11", "estadio": "Nilton Santos" },
    { "mandante": "Santos", "visitante": "Botafogo", "golsMandante": 4, "golsVisitante": 1, "campeonato": "Brasileirão 2019", "data": "2019-11-03", "estadio": "Vila Belmiro" },
    { "mandante": "Botafogo", "visitante": "Cruzeiro", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Brasileirão 2019", "data": "2019-10-31", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "CSA", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2019", "data": "2019-10-21", "estadio": "Nilton Santos" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2019", "data": "2019-10-16", "estadio": "São Januário" },
    { "mandante": "Botafogo", "visitante": "Goiás", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Brasileirão 2019", "data": "2019-10-09", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2019", "data": "2019-10-06", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "São Paulo", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Brasileirão 2019", "data": "2019-09-21", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2019", "data": "2019-09-08", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Chapecoense", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2019", "data": "2019-08-26", "estadio": "Nilton Santos" },
    { "mandante": "Corinthians", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2019", "data": "2019-08-17", "estadio": "Neo Química Arena" },
    { "mandante": "Botafogo", "visitante": "Athletico-PR", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2019", "data": "2019-08-11", "estadio": "Nilton Santos" },
    { "mandante": "Atlético-MG", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Copa Sul-Americana 2019", "data": "2019-07-31", "estadio": "Independência" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 3, "golsVisitante": 2, "campeonato": "Brasileirão 2019", "data": "2019-07-28", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Copa Sul-Americana 2019", "data": "2019-07-24", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Santos", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2019", "data": "2019-07-21", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2019", "data": "2019-06-02", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Sol de America", "golsMandante": 4, "golsVisitante": 0, "campeonato": "Copa Sul-Americana 2019", "data": "2019-05-29", "estadio": "Nilton Santos" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2019", "data": "2019-05-11", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Fortaleza", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2019", "data": "2019-05-05", "estadio": "Nilton Santos" },
    { "mandante": "São Paulo", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2019", "data": "2019-04-27", "estadio": "Morumbi" },
    { "mandante": "Botafogo", "visitante": "Juventude", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Copa do Brasil 2019", "data": "2019-04-04", "estadio": "Nilton Santos" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Carioca 2019", "data": "2019-03-17", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Madureira", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2019", "data": "2019-03-11", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Cuiabá", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Copa do Brasil 2019", "data": "2019-02-27", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Carioca 2019", "data": "2019-02-23", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Defensa y Justicia", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Copa Sul-Americana 2019", "data": "2019-02-06", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Resende", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Carioca 2019", "data": "2019-01-31", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Bangu", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Carioca 2019", "data": "2019-01-23", "estadio": "Nilton Santos" },
    jogos.push({ "mandante": "Botafogo", "visitante": "Paraná", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2018", "data": "2018-11-26", "estadio": "Nilton Santos" }),
    { "mandante": "Botafogo", "visitante": "Internacional", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2018", "data": "2018-11-18", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Flamengo", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2018", "data": "2018-11-10", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Corinthians", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2018", "data": "2018-11-04", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Bahia", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2018", "data": "2018-10-20", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2018", "data": "2018-10-09", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Bahia", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Copa Sul-Americana 2018", "data": "2018-10-03", "estadio": "Nilton Santos", "penaltis": "4 x 5" },
    { "mandante": "Botafogo", "visitante": "São Paulo", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Brasileirão 2018", "data": "2018-09-30", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "América-MG", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2018", "data": "2018-09-16", "estadio": "Nilton Santos" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2018", "data": "2018-09-09", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Cruzeiro", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2018", "data": "2018-09-05", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Sport", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2018", "data": "2018-08-25", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 0, "golsVisitante": 3, "campeonato": "Brasileirão 2018", "data": "2018-08-19", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Nacional-PAR", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Copa Sul-Americana 2018", "data": "2018-08-16", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Santos", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2018", "data": "2018-08-04", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Chapecoense", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2018", "data": "2018-07-26", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Ceará", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2018", "data": "2018-06-06", "estadio": "Nilton Santos" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Brasileirão 2018", "data": "2018-06-02", "estadio": "São Januário" },
    { "mandante": "Botafogo", "visitante": "Vitória", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2018", "data": "2018-05-27", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2018", "data": "2018-05-14", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Audax Italiano", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Copa Sul-Americana 2018", "data": "2018-05-09", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Grêmio", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2018", "data": "2018-04-28", "estadio": "Nilton Santos" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Carioca 2018", "data": "2018-04-08", "estadio": "Maracanã", "penaltis": "3 x 4" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 2, "golsVisitante": 3, "campeonato": "Carioca 2018", "data": "2018-04-01", "estadio": "Nilton Santos" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Carioca 2018", "data": "2018-03-28", "estadio": "Maracanã" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Carioca 2018", "data": "2018-03-25", "estadio": "Maracanã" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 3, "campeonato": "Carioca 2018", "data": "2018-03-21", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 2, "golsVisitante": 3, "campeonato": "Carioca 2018", "data": "2018-03-18", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Bangu", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2018", "data": "2018-03-06", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Madureira", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Carioca 2018", "data": "2018-02-03", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Boavista", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2018", "data": "2018-01-28", "estadio": "Nilton Santos" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Carioca 2018", "data": "2018-01-20", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Portuguesa-RJ", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Carioca 2018", "data": "2018-01-16", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Cruzeiro", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Brasileirão 2017", "data": "2017-12-03", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Atlético-GO", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Brasileirão 2017", "data": "2017-11-16", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Atlético-PR", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2017", "data": "2017-11-11", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Brasileirão 2017", "data": "2017-11-04", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Corinthians", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2017", "data": "2017-10-23", "estadio": "Nilton Santos" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2017", "data": "2017-10-14", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Chapecoense", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2017", "data": "2017-10-11", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vitória", "golsMandante": 2, "golsVisitante": 3, "campeonato": "Brasileirão 2017", "data": "2017-10-01", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Santos", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2017", "data": "2017-09-16", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Grêmio", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Libertadores 2017", "data": "2017-09-13", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Flamengo", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2017", "data": "2017-09-10", "estadio": "Nilton Santos" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Copa do Brasil 2017", "data": "2017-08-23", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Flamengo", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Copa do Brasil 2017", "data": "2017-08-16", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Grêmio", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2017", "data": "2017-08-13", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Nacional-URU", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Libertadores 2017", "data": "2017-08-10", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Palmeiras", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Brasileirão 2017", "data": "2017-08-02", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "São Paulo", "golsMandante": 3, "golsVisitante": 4, "campeonato": "Brasileirão 2017", "data": "2017-07-29", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Copa do Brasil 2017", "data": "2017-07-26", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Sport", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2017", "data": "2017-07-17", "estadio": "Nilton Santos" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2017", "data": "2017-07-12", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2017", "data": "2017-07-09", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Avaí", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Brasileirão 2017", "data": "2017-06-26", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Brasileirão 2017", "data": "2017-06-21", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Coritiba", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Brasileirão 2017", "data": "2017-06-11", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Bahia", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2017", "data": "2017-05-28", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Ponte Preta", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2017", "data": "2017-05-21", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Atlético Nacional", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Libertadores 2017", "data": "2017-05-18", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Barcelona de Guayaquil", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Libertadores 2017", "data": "2017-05-02", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Sport", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Copa do Brasil 2017", "data": "2017-04-26", "estadio": "Nilton Santos" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2017", "data": "2017-04-16", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Carioca 2017", "data": "2017-04-09", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 2, "golsVisitante": 3, "campeonato": "Carioca 2017", "data": "2017-03-23", "estadio": "Nilton Santos" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Carioca 2017", "data": "2017-03-19", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Volta Redonda", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2017", "data": "2017-03-09", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Olimpia", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Libertadores 2017", "data": "2017-02-15", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Macaé", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2017", "data": "2017-02-04", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Colo-Colo", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Libertadores 2017", "data": "2017-02-01", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Nova Iguaçu", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Carioca 2017", "data": "2017-01-28", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Ponte Preta", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2016", "data": "2016-11-26", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Chapecoense", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Brasileirão 2016", "data": "2016-11-16", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Coritiba", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Brasileirão 2016", "data": "2016-10-29", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 3, "golsVisitante": 2, "campeonato": "Brasileirão 2016", "data": "2016-10-16", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Internacional", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2016", "data": "2016-10-12", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2016", "data": "2016-09-07", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Grêmio", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2016", "data": "2016-09-04", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Palmeiras", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Brasileirão 2016", "data": "2016-07-31", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Santa Cruz", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2016", "data": "2016-07-03", "estadio": "Mário Helênio" },
    { "mandante": "Botafogo", "visitante": "São Paulo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2016", "data": "2016-05-15", "estadio": "Raulino de Oliveira" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Carioca 2016", "data": "2016-05-08", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Carioca 2016", "data": "2016-05-01", "estadio": "Maracanã" },
    { "mandante": "Boavista", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Carioca 2016", "data": "2016-03-06", "estadio": "São Januário" },
    { "mandante": "Botafogo", "visitante": "Portuguesa-RJ", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2016", "data": "2016-02-02", "estadio": "São Januário" },
    { "mandante": "Botafogo", "visitante": "América-MG", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Série B 2015", "data": "2015-11-28", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Santa Cruz", "golsMandante": 0, "golsVisitante": 3, "campeonato": "Série B 2015", "data": "2015-11-14", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Bragantino", "golsMandante": 4, "golsVisitante": 0, "campeonato": "Série B 2015", "data": "2015-10-17", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Paysandu", "golsMandante": 2, "golsVisitante": 3, "campeonato": "Série B 2015", "data": "2015-08-23", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Criciúma", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Série B 2015", "data": "2015-07-28", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Figueirense", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Copa do Brasil 2015", "data": "2015-07-14", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Boa Esporte", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Série B 2015", "data": "2015-06-19", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Mogi Mirim", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Série B 2015", "data": "2015-06-05", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vitória", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Série B 2015", "data": "2015-05-30", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "CRB", "golsMandante": 4, "golsVisitante": 1, "campeonato": "Série B 2015", "data": "2015-05-16", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Carioca 2015", "data": "2015-05-03", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Madureira", "golsMandante": 4, "golsVisitante": 1, "campeonato": "Carioca 2015", "data": "2015-04-05", "estadio": "Nilton Santos" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Carioca 2015", "data": "2015-03-29", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Resende", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Carioca 2015", "data": "2015-03-15", "estadio": "Nilton Santos" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Carioca 2015", "data": "2015-03-08", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Flamengo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2015", "data": "2015-03-01", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Nova Iguaçu", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2015", "data": "2015-02-21", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Bonsucesso", "golsMandante": 4, "golsVisitante": 0, "campeonato": "Carioca 2015", "data": "2015-02-07", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Boavista", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2015", "data": "2015-01-31", "estadio": "São Januário" },
    { "mandante": "Botafogo", "visitante": "Palmeiras", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2014", "data": "2014-10-08", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Bahia", "golsMandante": 2, "golsVisitante": 3, "campeonato": "Brasileirão 2014", "data": "2014-09-17", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Santos", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2014", "data": "2014-08-31", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Chapecoense", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2014", "data": "2014-08-23", "estadio": "Maracanã" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2014", "data": "2014-07-27", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Independiente Del Valle", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Libertadores 2014", "data": "2014-03-18", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Deportivo Quito", "golsMandante": 4, "golsVisitante": 0, "campeonato": "Libertadores 2014", "data": "2014-02-05", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Criciúma", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Brasileirão 2013", "data": "2013-12-08", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Grêmio", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2013", "data": "2013-10-05", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2013", "data": "2013-05-05", "estadio": "Raulino de Oliveira" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Carioca 2013", "data": "2013-02-17", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Carioca 2012", "data": "2012-04-29", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Bahia", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Brasileirão 2011", "data": "2011-10-08", "estadio": "São Januário" },
    { "mandante": "Botafogo", "visitante": "Ceará", "golsMandante": 4, "golsVisitante": 0, "campeonato": "Brasileirão 2011", "data": "2011-09-07", "estadio": "Nilton Santos" },
    { "mandante": "Vasco", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Carioca 2011", "data": "2011-03-20", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Volta Redonda", "golsMandante": 4, "golsVisitante": 2, "campeonato": "Carioca 2011", "data": "2011-03-05", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vitória", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2010", "data": "2010-10-23", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Brasileirão 2010", "data": "2010-08-07", "estadio": "Nilton Santos" },
    { "mandante": "Boavista", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 4, "campeonato": "Carioca 2010", "data": "2010-03-29", "estadio": "São Januário" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2009", "data": "2009-03-28", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Náutico", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2008", "data": "2008-08-30", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2008", "data": "2008-05-25", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Atlético-MG", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Copa do Brasil 2008", "data": "2008-05-14", "estadio": "Nilton Santos" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Carioca 2008", "data": "2008-03-30", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 0, "golsVisitante": 2, "campeonato": "Brasileirão 2007", "data": "2007-09-23", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Internacional", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2007", "data": "2007-08-19", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Náutico", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Brasileirão 2007", "data": "2007-06-17", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Grêmio", "golsMandante": 3, "golsVisitante": 0, "campeonato": "Brasileirão 2007", "data": "2007-06-02", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Figueirense", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Copa do Brasil 2007", "data": "2007-05-23", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Goiás", "golsMandante": 2, "golsVisitante": 2, "campeonato": "Brasileirão 2006", "data": "2006-11-19", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Internacional", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Brasileirão 2006", "data": "2006-11-02", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "São Caetano", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Brasileirão 2006", "data": "2006-10-22", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Santos", "golsMandante": 4, "golsVisitante": 3, "campeonato": "Brasileirão 2006", "data": "2006-10-14", "estadio": "Maracanã" },
    { "mandante": "Madureira", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 3, "campeonato": "Carioca 2006", "data": "2006-04-09", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Nova Iguaçu", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Carioca 2006", "data": "2006-02-19", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Vasco", "golsMandante": 5, "golsVisitante": 3, "campeonato": "Carioca 2006", "data": "2006-01-22", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Paraná", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2005", "data": "2005-11-12", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Palmeiras", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Brasileirão 2005", "data": "2005-10-08", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Goiás", "golsMandante": 3, "golsVisitante": 1, "campeonato": "Brasileirão 2005", "data": "2005-09-18", "estadio": "Luso Brasileiro" },
    { "mandante": "Botafogo", "visitante": "Atlético-PR", "golsMandante": 2, "golsVisitante": 0, "campeonato": "Brasileirão 2005", "data": "2005-05-29", "estadio": "Luso Brasileiro" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 4, "golsVisitante": 0, "campeonato": "Carioca 2005", "data": "2005-03-13", "estadio": "Maracanã" },
    { "mandante": "Americano", "visitante": "Botafogo", "golsMandante": 2, "golsVisitante": 1, "campeonato": "Carioca 2005", "data": "2005-02-13", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Corinthians", "golsMandante": 1, "golsVisitante": 2, "campeonato": "Brasileirão 2004", "data": "2004-12-12", "estadio": "Caio Martins" },
    { "mandante": "Botafogo", "visitante": "Guarani", "golsMandante": 1, "golsVisitante": 0, "campeonato": "Brasileirão 2004", "data": "2004-11-27", "estadio": "Caio Martins" },
    { "mandante": "Botafogo", "visitante": "Coritiba", "golsMandante": 4, "golsVisitante": 1, "campeonato": "Brasileirão 2004", "data": "2004-11-13", "estadio": "Caio Martins" },
    { "mandante": "Fluminense", "visitante": "Botafogo", "golsMandante": 1, "golsVisitante": 4, "campeonato": "Brasileirão 2004", "data": "2004-10-02", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Criciúma", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2004", "data": "2004-08-28", "estadio": "Caio Martins" },
    { "mandante": "Botafogo", "visitante": "Atlético-PR", "golsMandante": 1, "golsVisitante": 1, "campeonato": "Brasileirão 2004", "data": "2004-08-12", "estadio": "Caio Martins" },
    { "mandante": "Flamengo", "visitante": "Botafogo", "golsMandante": 0, "golsVisitante": 1, "campeonato": "Carioca 2004", "data": "2004-03-14", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 0, "golsVisitante": 0, "campeonato": "Carioca 2004", "data": "2004-02-29", "estadio": "Maracanã" },
    { "mandante": "Botafogo", "visitante": "Fluminense", "golsMandante": 2, "golsVisitante": 3, "campeonato": "Brasileirão 2002", "data": "2002-10-26", "estadio": "Maracanã" }
];

export default jogos;